# Generated by Django 5.2.1 on 2026-01-08 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("shipping_first_name", models.CharField(max_length=100)),
                ("shipping_last_name", models.CharField(max_length=100)),
                ("shipping_address_line_1", models.CharField(max_length=255)),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_postal_code", models.CharField(max_length=20)),
                ("shipping_country", models.CharField(max_length=100)),
                ("billing_first_name", models.CharField(max_length=100)),
                ("billing_last_name", models.CharField(max_length=100)),
                ("billing_address_line_1", models.CharField(max_length=255)),
                (
                    "billing_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("billing_city", models.CharField(max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_postal_code", models.CharField(max_length=20)),
                ("billing_country", models.CharField(max_length=100)),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping"),
                            ("express", "Express Shipping"),
                            ("overnight", "Overnight Shipping"),
                        ],
                        db_index=True,
                        default="standard",
                        help_text="Shipping method chosen for this order",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit Card (Stripe)"),
                            ("paypal", "PayPal"),
                        ],
                        db_index=True,
                        default="stripe",
                        help_text="Payment method used for this order",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order subtotal in BDT",
                        max_digits=10,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount applied",
                        max_digits=10,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax amount applied",
                        max_digits=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, help_text="Order total in BDT", max_digits=10
                    ),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                ("customer_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("is_gift", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, max_length=500)),
                ("gift_wrap", models.BooleanField(default=False)),
                (
                    "gift_wrap_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft-delete flag; delete is logical",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the order was soft-deleted",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_sku", models.CharField(blank=True, max_length=100)),
                ("variant_name", models.CharField(blank=True, max_length=255)),
                ("product_image", models.URLField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
