# Generated by Django 5.2.10 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_currency_order_exchange_rate"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "orders_order" '
                        'ADD COLUMN IF NOT EXISTS "currency" varchar(3) '
                        "NOT NULL DEFAULT 'BDT';"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "orders_order" '
                        'DROP COLUMN IF EXISTS "currency";'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "orders_order" '
                        'ADD COLUMN IF NOT EXISTS "exchange_rate" numeric(10, 6) '
                        "NOT NULL DEFAULT 1;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "orders_order" '
                        'DROP COLUMN IF EXISTS "exchange_rate";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="currency",
                    field=models.CharField(default="BDT", max_length=3),
                ),
                migrations.AddField(
                    model_name="order",
                    name="exchange_rate",
                    field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
                ),
            ],
        ),
    ]
