# Generated by Django 5.2.11 on 2026-04-19 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_product_catalog_prod_active_created_and_more"),
        ("contacts", "0007_alter_contactattachment_file_and_more"),
        ("orders", "0003_historicalorder_historicalorderitem_and_more"),
        ("promotions", "0013_banner_animation_type_banner_autoplay_delay_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_deleted", "-created_at"], name="orders_deleted_at"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="orders_user_status"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product_id"], name="orders_orde_order_i_52f79a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="orders_orde_order_i_5d347b_idx"),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "-created_at"], name="orders_orde_order_i_ca028d_idx"
            ),
        ),
    ]
