# Generated by Django 5.2.11 on 2026-02-09 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Env Category",
                "verbose_name_plural": "Env Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EnvVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_secret", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=False)),
                ("restart_required", models.BooleanField(default=False)),
                ("runtime_apply", models.BooleanField(default=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("targets", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variables",
                        to="env_registry.envcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Env Variable",
                "verbose_name_plural": "Env Variables",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="EnvValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("production", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value_plain", models.TextField(blank=True)),
                ("value_encrypted", models.BinaryField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="env_values_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="env_registry.envvariable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Env Value",
                "verbose_name_plural": "Env Values",
                "ordering": ["variable__key", "environment"],
                "unique_together": {("variable", "environment")},
            },
        ),
    ]
