# Generated by Django 5.2.1 on 2026-01-09 11:22

import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Key Name")),
                (
                    "key_prefix",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="Key Prefix"
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, verbose_name="Key Hash")),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("full", "Full Access"),
                            ("mail_send", "Mail Send Only"),
                            ("read", "Read Only"),
                            ("templates", "Templates Only"),
                        ],
                        default="mail_send",
                        max_length=20,
                        verbose_name="Permission",
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of IP addresses allowed to use this key",
                        verbose_name="Allowed IPs",
                    ),
                ),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=100)),
                ("rate_limit_per_hour", models.PositiveIntegerField(default=1000)),
                ("rate_limit_per_day", models.PositiveIntegerField(default=10000)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Message ID",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(max_length=254, verbose_name="From Email"),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="From Name"
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Reply To"
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="To Email"
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="To Name"
                    ),
                ),
                ("cc", models.JSONField(blank=True, default=list, verbose_name="CC")),
                ("bcc", models.JSONField(blank=True, default=list, verbose_name="BCC")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("html_body", models.TextField(blank=True, verbose_name="HTML Body")),
                ("text_body", models.TextField(blank=True, verbose_name="Text Body")),
                (
                    "template_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Template Data"
                    ),
                ),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="Has Attachments"),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Custom Headers"
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Categories"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Sender IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("dropped", "Dropped"),
                            ("spam", "Marked as Spam"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hard", "Hard Bounce"),
                            ("soft", "Soft Bounce"),
                            ("block", "Blocked"),
                        ],
                        max_length=10,
                        verbose_name="Bounce Type",
                    ),
                ),
                (
                    "bounce_reason",
                    models.TextField(blank=True, verbose_name="Bounce Reason"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled At"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First Opened"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First Clicked"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Attempt Count"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Attempt"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Retry"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "smtp_response",
                    models.TextField(blank=True, verbose_name="SMTP Response"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="email_service.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content Type"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="Size (bytes)")),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="email_attachments/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Content ID"
                    ),
                ),
                (
                    "is_inline",
                    models.BooleanField(
                        default=False, verbose_name="Inline Attachment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="email_service.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "template_id",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Template ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Subject Line"),
                ),
                (
                    "html_content",
                    models.TextField(blank=True, verbose_name="HTML Content"),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Text Content"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("text", "Plain Text"),
                            ("both", "HTML & Text"),
                        ],
                        default="html",
                        max_length=10,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variable names used in the template",
                        verbose_name="Template Variables",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="System Template"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["name"],
                "unique_together": {("user", "template_id")},
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="email_service.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="SenderDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Domain"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(max_length=64, verbose_name="Verification Token"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "dns_records",
                    models.JSONField(
                        default=dict,
                        help_text="Required DNS records for verification",
                        verbose_name="DNS Records",
                    ),
                ),
                (
                    "dkim_selector",
                    models.CharField(
                        default="bunoraa", max_length=50, verbose_name="DKIM Selector"
                    ),
                ),
                (
                    "dkim_public_key",
                    models.TextField(blank=True, verbose_name="DKIM Public Key"),
                ),
                (
                    "dkim_private_key",
                    models.TextField(blank=True, verbose_name="DKIM Private Key"),
                ),
                (
                    "dkim_verified",
                    models.BooleanField(default=False, verbose_name="DKIM Verified"),
                ),
                (
                    "spf_verified",
                    models.BooleanField(default=False, verbose_name="SPF Verified"),
                ),
                (
                    "dmarc_verified",
                    models.BooleanField(default=False, verbose_name="DMARC Verified"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Domain"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Checked"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sender Domain",
                "verbose_name_plural": "Sender Domains",
                "ordering": ["-is_default", "domain"],
            },
        ),
        migrations.CreateModel(
            name="SenderIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(max_length=100, verbose_name="From Name"),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Reply To"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(max_length=64, verbose_name="Verification Token"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Identity"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="email_service.senderdomain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sender Identity",
                "verbose_name_plural": "Sender Identities",
                "ordering": ["-is_default", "email"],
            },
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "suppression_type",
                    models.CharField(
                        choices=[
                            ("bounce_hard", "Hard Bounce"),
                            ("bounce_soft", "Soft Bounce"),
                            ("spam", "Spam Report"),
                            ("unsubscribe", "Unsubscribe"),
                            ("manual", "Manually Added"),
                            ("invalid", "Invalid Email"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removed At"
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="email_service.emailmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suppression",
                "verbose_name_plural": "Suppressions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Subject Line"),
                ),
                (
                    "html_content",
                    models.TextField(blank=True, verbose_name="HTML Content"),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Text Content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_notes",
                    models.TextField(blank=True, verbose_name="Change Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="email_service.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Version",
                "verbose_name_plural": "Template Versions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="UnsubscribeGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Group"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unsubscribe Group",
                "verbose_name_plural": "Unsubscribe Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnsubscribePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "is_unsubscribed",
                    models.BooleanField(default=True, verbose_name="Unsubscribed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="email_service.unsubscribegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unsubscribe Preference",
                "verbose_name_plural": "Unsubscribe Preferences",
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Webhook Name")),
                ("url", models.URLField(max_length=500, verbose_name="Webhook URL")),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event types to trigger this webhook",
                        verbose_name="Events",
                    ),
                ),
                (
                    "secret",
                    models.CharField(max_length=64, verbose_name="Signing Secret"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "total_sent",
                    models.PositiveIntegerField(default=0, verbose_name="Total Sent"),
                ),
                (
                    "total_failed",
                    models.PositiveIntegerField(default=0, verbose_name="Total Failed"),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sent"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="Last Error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event Type"),
                ),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Response Status"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Response Body"),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Response Time (ms)"
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="Success")),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Attempt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="email_service.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Date")),
                ("sent", models.PositiveIntegerField(default=0, verbose_name="Sent")),
                (
                    "delivered",
                    models.PositiveIntegerField(default=0, verbose_name="Delivered"),
                ),
                (
                    "opened",
                    models.PositiveIntegerField(default=0, verbose_name="Opened"),
                ),
                (
                    "clicked",
                    models.PositiveIntegerField(default=0, verbose_name="Clicked"),
                ),
                (
                    "bounced",
                    models.PositiveIntegerField(default=0, verbose_name="Bounced"),
                ),
                (
                    "dropped",
                    models.PositiveIntegerField(default=0, verbose_name="Dropped"),
                ),
                (
                    "spam_reports",
                    models.PositiveIntegerField(default=0, verbose_name="Spam Reports"),
                ),
                (
                    "unsubscribes",
                    models.PositiveIntegerField(default=0, verbose_name="Unsubscribes"),
                ),
                (
                    "unique_opens",
                    models.PositiveIntegerField(default=0, verbose_name="Unique Opens"),
                ),
                (
                    "unique_clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Unique Clicks"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Statistics",
                "verbose_name_plural": "Daily Statistics",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("deferred", "Deferred"),
                            ("bounced", "Bounced"),
                            ("dropped", "Dropped"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("spam", "Spam Report"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Clicked URL"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=2, verbose_name="Country"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Region"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Device Type"
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="Browser"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Operating System"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Event Data"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="email_service.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Event",
                "verbose_name_plural": "Email Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message", "event_type", "timestamp"],
                        name="email_servi_message_cf90c9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="email_servi_user_id_6330e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["to_email", "created_at"], name="email_servi_to_emai_5f8ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["status", "next_retry_at"], name="email_servi_status_5d72f1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="suppression",
            unique_together={("user", "email", "suppression_type")},
        ),
        migrations.AlterUniqueTogether(
            name="templateversion",
            unique_together={("template", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="unsubscribepreference",
            unique_together={("email", "group")},
        ),
    ]
