# Generated by Django 5.2.11 on 2026-04-04 02:46

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_historicalapikey_historicaldailystats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='email_attachments/%Y/%m/', verbose_name='File'),
        ),
    ]
