# Generated by Django 5.2.11 on 2026-04-04 03:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_service", "0003_alter_emailattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="email_attachments/%Y/%m/",
                verbose_name="File",
            ),
        ),
    ]
