# Generated by Django 5.2.11 on 2026-02-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_interactions",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_interactions",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="accounts.usersession",
            ),
        ),
        migrations.AddField(
            model_name="webauthnchallenge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webauthn_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webauthn_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4734df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="accounts_us_is_acti_d91a15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(fields=["status"], name="accounts_ac_status_929d86_idx"),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(
                fields=["scheduled_for"], name="accounts_ac_schedul_1014c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_default"], name="accounts_ad_user_id_c8244c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "address_type"], name="accounts_ad_user_id_3561c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexportjob",
            index=models.Index(
                fields=["user", "-requested_at"], name="accounts_da_user_id_181966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexportjob",
            index=models.Index(fields=["status"], name="accounts_da_status_7316a4_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["token"], name="accounts_em_token_5f2b37_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token"], name="accounts_pa_token_affdf2_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "used"], name="accounts_pa_user_id_fbc669_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["engagement_score"], name="accounts_us_engagem_ac9960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["loyalty_score"], name="accounts_us_loyalty_005d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["cluster_id"], name="accounts_us_cluster_332e8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["last_active"], name="accounts_us_last_ac_66b27c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="accounts_us_session_511f42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-started_at"], name="accounts_us_user_id_9b48aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["-started_at"], name="accounts_us_started_111903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["country_code"], name="accounts_us_country_c82f58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "session_type", "-started_at"],
                name="accounts_us_user_id_25adb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "interaction_type", "-created_at"],
                name="accounts_us_user_id_148a08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["product", "-created_at"], name="accounts_us_product_d15056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["category", "-created_at"],
                name="accounts_us_categor_95a962_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["interaction_type", "-created_at"],
                name="accounts_us_interac_aafe2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webauthnchallenge",
            index=models.Index(
                fields=["challenge", "challenge_type"],
                name="accounts_we_challen_ff788d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webauthnchallenge",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_we_user_id_3953b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_we_user_id_0b5d43_idx"
            ),
        ),
    ]
