# Generated by Django 5.2.11 on 2026-02-09 21:29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_security_privacy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountdeletionrequest",
            new_name="accounts_ac_status_929d86_idx",
            old_name="accounts_ac_status_7bcb60_idx",
        ),
        migrations.RenameIndex(
            model_name="accountdeletionrequest",
            new_name="accounts_ac_schedul_1014c2_idx",
            old_name="accounts_ac_schedule_0f9d50_idx",
        ),
        migrations.RenameIndex(
            model_name="dataexportjob",
            new_name="accounts_da_user_id_181966_idx",
            old_name="accounts_da_user_id_eb927a_idx",
        ),
        migrations.RenameIndex(
            model_name="dataexportjob",
            new_name="accounts_da_status_7316a4_idx",
            old_name="accounts_da_status_1b9c6a_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="accounts_us_user_id_25adb9_idx",
            old_name="accounts_us_user_id_8b7b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="webauthnchallenge",
            new_name="accounts_we_challen_ff788d_idx",
            old_name="accounts_we_challen_5d64e5_idx",
        ),
        migrations.RenameIndex(
            model_name="webauthnchallenge",
            new_name="accounts_we_user_id_3953b7_idx",
            old_name="accounts_we_user_id_79a4bf_idx",
        ),
        migrations.RenameIndex(
            model_name="webauthncredential",
            new_name="accounts_we_user_id_0b5d43_idx",
            old_name="accounts_we_user_id_585f6c_idx",
        ),
        migrations.AlterField(
            model_name="dataexportjob",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="exports/",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("moonlight", "Moonlight"),
                    ("gray", "Gray"),
                    ("modern", "Modern"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
