# Generated by Django 5.2.11 on 2026-04-08 05:02

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_dataexportjob_file_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexportjob",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="exports/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="avatars/",
                verbose_name="avatar",
            ),
        ),
    ]
