# Generated by Django 5.2.11 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_dataexportjob_file_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexportjob",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="exports/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="avatar"
            ),
        ),
    ]
