# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="IANA timezone name (e.g., Asia/Dhaka)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="User-friendly name", max_length=200),
                ),
                (
                    "offset",
                    models.CharField(
                        help_text="UTC offset (e.g., +06:00)", max_length=10
                    ),
                ),
                (
                    "offset_minutes",
                    models.IntegerField(
                        default=0, help_text="Offset in minutes for sorting"
                    ),
                ),
                (
                    "has_dst",
                    models.BooleanField(
                        default=False, help_text="Has daylight saving time"
                    ),
                ),
                (
                    "dst_offset",
                    models.CharField(blank=True, help_text="DST offset", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_common",
                    models.BooleanField(
                        default=False, help_text="Show in common timezones list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Timezone",
                "verbose_name_plural": "Timezones",
                "ordering": ["offset_minutes", "name"],
            },
        ),
        migrations.CreateModel(
            name="TranslationNamespace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Translation Namespace",
                "verbose_name_plural": "Translation Namespaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 4217 currency code (e.g., USD, BDT)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Currency name", max_length=100)),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., $, ৳)", max_length=10
                    ),
                ),
                (
                    "native_symbol",
                    models.CharField(
                        blank=True,
                        help_text="Native symbol if different",
                        max_length=10,
                    ),
                ),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "symbol_position",
                    models.CharField(
                        choices=[
                            ("before", "Before amount ($100)"),
                            ("before_space", "Before with space ($ 100)"),
                            ("after", "After amount (100$)"),
                            ("after_space", "After with space (100 $)"),
                        ],
                        default="before",
                        max_length=20,
                    ),
                ),
                ("thousand_separator", models.CharField(default=",", max_length=5)),
                ("decimal_separator", models.CharField(default=".", max_length=5)),
                (
                    "number_system",
                    models.CharField(
                        choices=[
                            ("western", "Western (1,234.56)"),
                            ("indian", "Indian (1,23,456.78)"),
                            ("bengali", "Bengali numerals"),
                        ],
                        default="western",
                        max_length=20,
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False,
                        help_text="Use as base for exchange rate calculations",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="i18n_curren_code_d60298_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="i18n_curren_is_defa_ee7773_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 code",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "code_alpha3",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-3 code", max_length=3
                    ),
                ),
                (
                    "code_numeric",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 numeric code", max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        help_text="International dialing code",
                        max_length=10,
                    ),
                ),
                (
                    "phone_format",
                    models.CharField(
                        blank=True,
                        help_text="Phone format pattern (e.g., +880 XXXX-XXXXXX)",
                        max_length=50,
                    ),
                ),
                (
                    "address_format",
                    models.TextField(blank=True, help_text="Address format template"),
                ),
                (
                    "postal_code_format",
                    models.CharField(
                        blank=True, help_text="Postal code regex pattern", max_length=50
                    ),
                ),
                ("vat_number_format", models.CharField(blank=True, max_length=50)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Default VAT/GST rate",
                        max_digits=5,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("africa", "Africa"),
                            ("antarctica", "Antarctica"),
                            ("asia", "Asia"),
                            ("europe", "Europe"),
                            ("north_america", "North America"),
                            ("oceania", "Oceania"),
                            ("south_america", "South America"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Sub-region (e.g., South Asia)",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                ("is_billing_allowed", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_countries",
                        to="i18n.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Division code (e.g., DHK)", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "division_type",
                    models.CharField(
                        choices=[
                            ("division", "Division"),
                            ("state", "State"),
                            ("province", "Province"),
                            ("region", "Region"),
                            ("territory", "Territory"),
                        ],
                        default="division",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                ("shipping_zone", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="i18n.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "ordering": ["sort_order", "name"],
                "unique_together": {("country", "code")},
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="District code", max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                (
                    "shipping_zone",
                    models.CharField(
                        choices=[
                            ("metro", "Metro/City"),
                            ("suburban", "Suburban"),
                            ("rural", "Rural"),
                            ("remote", "Remote"),
                        ],
                        default="suburban",
                        help_text="Used for shipping rate calculation",
                        max_length=20,
                    ),
                ),
                ("estimated_delivery_days_min", models.PositiveIntegerField(default=2)),
                ("estimated_delivery_days_max", models.PositiveIntegerField(default=5)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="i18n.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["sort_order", "name"],
                "unique_together": {("division", "code")},
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Language code (e.g., en, bn, hi)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English", max_length=100
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Language name in native script", max_length=100
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(
                        default=False, help_text="Right-to-left language"
                    ),
                ),
                (
                    "flag_code",
                    models.CharField(
                        blank=True,
                        help_text="Country code for flag icon",
                        max_length=10,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        blank=True,
                        help_text="CSS font-family for this language",
                        max_length=200,
                    ),
                ),
                (
                    "locale_code",
                    models.CharField(
                        blank=True,
                        help_text="Full locale code (e.g., en_US, bn_BD)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "translation_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentage of translations complete (0-100)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("total_strings", models.PositiveIntegerField(default=0)),
                ("translated_strings", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="i18n_langua_code_bda953_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="i18n_langua_is_defa_4b77d5_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="country",
            name="default_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_countries",
                to="i18n.language",
            ),
        ),
        migrations.CreateModel(
            name="I18nSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("show_language_selector", models.BooleanField(default=True)),
                ("auto_detect_currency", models.BooleanField(default=True)),
                ("show_currency_selector", models.BooleanField(default=True)),
                (
                    "show_original_price",
                    models.BooleanField(
                        default=False,
                        help_text="Show original price alongside converted price",
                    ),
                ),
                ("auto_detect_timezone", models.BooleanField(default=True)),
                ("show_timezone_selector", models.BooleanField(default=False)),
                ("auto_update_exchange_rates", models.BooleanField(default=True)),
                (
                    "exchange_rate_update_frequency",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours between updates"
                    ),
                ),
                (
                    "exchange_rate_provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("openexchange", "Open Exchange Rates"),
                            ("fixer", "Fixer.io"),
                            ("ecb", "European Central Bank"),
                            ("exchangerate_api", "ExchangeRate-API"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("exchange_rate_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "last_exchange_rate_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("none", "No rounding"),
                            ("nearest_cent", "Nearest cent"),
                            ("nearest_99", "Nearest .99"),
                            ("nearest_95", "Nearest .95"),
                            ("nearest_integer", "Nearest whole number"),
                            ("round_up", "Always round up"),
                        ],
                        default="nearest_cent",
                        max_length=20,
                    ),
                ),
                ("enable_machine_translation", models.BooleanField(default=False)),
                (
                    "translation_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Translate"),
                            ("deepl", "DeepL"),
                            ("azure", "Azure Translator"),
                            ("aws", "Amazon Translate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("translation_api_key", models.CharField(blank=True, max_length=255)),
                ("auto_translate_new_content", models.BooleanField(default=False)),
                (
                    "require_human_review",
                    models.BooleanField(
                        default=True,
                        help_text="Require human review for machine translations",
                    ),
                ),
                ("enable_geo_detection", models.BooleanField(default=True)),
                (
                    "geo_ip_provider",
                    models.CharField(
                        choices=[
                            ("cloudflare", "Cloudflare Headers"),
                            ("maxmind", "MaxMind GeoIP"),
                            ("ipinfo", "IPinfo"),
                        ],
                        default="cloudflare",
                        max_length=50,
                    ),
                ),
                ("geo_ip_api_key", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="i18n.currency",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="i18n.language",
                    ),
                ),
                (
                    "fallback_language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fallback if translation not available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="i18n.language",
                    ),
                ),
                (
                    "default_timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="i18n.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "I18n Settings",
                "verbose_name_plural": "I18n Settings",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="default_timezone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_countries",
                to="i18n.timezone",
            ),
        ),
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key (e.g., common.save_button)",
                        max_length=255,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(help_text="Source text in default language"),
                ),
                (
                    "context",
                    models.TextField(blank=True, help_text="Context for translators"),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum character length", null=True
                    ),
                ),
                (
                    "is_html",
                    models.BooleanField(default=False, help_text="Contains HTML"),
                ),
                (
                    "is_plural",
                    models.BooleanField(default=False, help_text="Has plural forms"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "namespace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="i18n.translationnamespace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Key",
                "verbose_name_plural": "Translation Keys",
                "ordering": ["namespace__name", "key"],
                "unique_together": {("namespace", "key")},
            },
        ),
        migrations.CreateModel(
            name="UserLocalePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                            ("DD.MM.YYYY", "DD.MM.YYYY"),
                            ("YYYY年MM月DD日", "YYYY年MM月DD日"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12-hour"), ("24h", "24-hour")],
                        default="12h",
                        max_length=10,
                    ),
                ),
                (
                    "first_day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        default=0,
                        help_text="0=Sunday, 1=Monday, etc.",
                    ),
                ),
                (
                    "measurement_system",
                    models.CharField(
                        choices=[("metric", "Metric"), ("imperial", "Imperial")],
                        default="metric",
                        max_length=10,
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(
                        choices=[("celsius", "Celsius"), ("fahrenheit", "Fahrenheit")],
                        default="celsius",
                        max_length=10,
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("auto_detect_currency", models.BooleanField(default=True)),
                ("auto_detect_timezone", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="i18n.country",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="i18n.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="i18n.language",
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="i18n.timezone",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="i18n_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Locale Preference",
                "verbose_name_plural": "User Locale Preferences",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Exchange rate (1 from_currency = rate to_currency)",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                (
                    "bid_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Buying rate",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "ask_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Selling rate",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("openexchange", "Open Exchange Rates"),
                            ("fixer", "Fixer.io"),
                            ("ecb", "European Central Bank"),
                            ("xe", "XE.com"),
                            ("currencylayer", "CurrencyLayer"),
                            ("exchangerate_api", "ExchangeRate-API"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="i18n.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="i18n.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "is_active"],
                        name="i18n_exchan_from_cu_71de28_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="i18n_exchan_valid_f_c3d176_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_currency", models.F("to_currency")), _negated=True
                        ),
                        name="different_currencies",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, help_text="Closing rate", max_digits=18
                    ),
                ),
                (
                    "open_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "high_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "low_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("source", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_from",
                        to="i18n.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_to",
                        to="i18n.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate History",
                "verbose_name_plural": "Exchange Rate History",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "date"],
                        name="i18n_exchan_from_cu_c6e475_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="ContentTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("category", "Category"),
                            ("page", "Page"),
                            ("email", "Email Template"),
                            ("notification", "Notification"),
                            ("banner", "Banner"),
                            ("menu", "Menu Item"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        db_index=True, help_text="UUID of the content", max_length=100
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field being translated", max_length=100
                    ),
                ),
                ("original_text", models.TextField(blank=True)),
                ("translated_text", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_machine_translated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_content_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_translations",
                        to="i18n.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Translation",
                "verbose_name_plural": "Content Translations",
                "ordering": ["content_type", "content_id", "field_name"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id", "language"],
                        name="i18n_conten_content_2ee031_idx",
                    )
                ],
                "unique_together": {
                    ("content_type", "content_id", "field_name", "language")
                },
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("translated_text", models.TextField()),
                (
                    "plural_forms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Plural translations: {0: 'zero', 1: 'one', 2: 'two', 'few': '...', 'many': '...', 'other': '...'}",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_machine_translated", models.BooleanField(default=False)),
                (
                    "quality_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Translation quality score (0-100)",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="i18n.language",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="i18n.translationkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "ordering": ["key__key", "language__code"],
                "unique_together": {("key", "language")},
            },
        ),
        migrations.CreateModel(
            name="Upazila",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Upazila code", max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "upazila_type",
                    models.CharField(
                        choices=[
                            ("upazila", "Upazila"),
                            ("thana", "Thana"),
                            ("municipality", "Municipality"),
                            ("city_corporation", "City Corporation"),
                            ("cantonment", "Cantonment"),
                        ],
                        default="upazila",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                (
                    "postal_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of postal codes for this upazila",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upazilas",
                        to="i18n.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upazila",
                "verbose_name_plural": "Upazilas",
                "ordering": ["sort_order", "name"],
                "unique_together": {("district", "code")},
            },
        ),
    ]
