# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of email addresses to receive inquiries",
                    ),
                ),
                ("auto_response_subject", models.CharField(blank=True, max_length=200)),
                ("auto_response_message", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Category",
                "verbose_name_plural": "Contact Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("general_email", models.EmailField(blank=True, max_length=254)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("sales_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("pinterest_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("allow_attachments", models.BooleanField(default=True)),
                ("max_attachment_size_mb", models.PositiveIntegerField(default=5)),
                (
                    "allowed_file_types",
                    models.CharField(
                        default="jpg,jpeg,png,pdf,doc,docx",
                        help_text="Comma-separated list of allowed file extensions",
                        max_length=255,
                    ),
                ),
                ("notify_on_new_inquiry", models.BooleanField(default=True)),
                (
                    "notification_emails",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of email addresses for notifications",
                    ),
                ),
                ("enable_auto_response", models.BooleanField(default=True)),
                (
                    "default_auto_response_subject",
                    models.CharField(blank=True, max_length=200),
                ),
                ("default_auto_response_message", models.TextField(blank=True)),
                (
                    "business_hours_note",
                    models.TextField(
                        blank=True,
                        help_text="Note about response times during business hours",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Settings",
                "verbose_name_plural": "Contact Settings",
            },
        ),
        migrations.CreateModel(
            name="StoreLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fax", models.CharField(blank=True, max_length=30)),
                ("monday_hours", models.CharField(blank=True, max_length=50)),
                ("tuesday_hours", models.CharField(blank=True, max_length=50)),
                ("wednesday_hours", models.CharField(blank=True, max_length=50)),
                ("thursday_hours", models.CharField(blank=True, max_length=50)),
                ("friday_hours", models.CharField(blank=True, max_length=50)),
                ("saturday_hours", models.CharField(blank=True, max_length=50)),
                ("sunday_hours", models.CharField(blank=True, max_length=50)),
                ("is_pickup_location", models.BooleanField(default=False)),
                ("is_returns_location", models.BooleanField(default=False)),
                (
                    "pickup_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_pickup_time_hours",
                    models.PositiveIntegerField(
                        default=2, help_text="Minimum hours before pickup is ready"
                    ),
                ),
                (
                    "max_hold_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Maximum days to hold for pickup"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="contacts/locations/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, help_text="Main/headquarters location"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Location",
                "verbose_name_plural": "Store Locations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("order_number", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "source_page",
                    models.URLField(
                        blank=True, help_text="Page from which the form was submitted"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("auto_response_sent", models.BooleanField(default=False)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="contacts.contactcategory",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="contacts/attachments/%Y/%m/",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contacts.contactinquiry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Attachment",
                "verbose_name_plural": "Contact Attachments",
            },
        ),
        migrations.CreateModel(
            name="ContactResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="contacts.contactinquiry",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Response",
                "verbose_name_plural": "Contact Responses",
                "ordering": ["-created_at"],
            },
        ),
    ]
