# Generated by Django 5.2.11 on 2026-04-04 03:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contactattachment_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/attachments/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="storelocation",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/locations/",
            ),
        ),
    ]
