# Generated by Django 5.2.11 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_alter_contactattachment_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattachment",
            name="file",
            field=models.FileField(upload_to="contacts/attachments/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="storelocation",
            name="image",
            field=models.ImageField(blank=True, upload_to="contacts/locations/"),
        ),
    ]
