# Generated by Django 5.2.1 on 2026-01-08 16:52

import apps.preorders.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreOrderCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS icon class",
                        max_length=50,
                        verbose_name="icon class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="preorder_categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum base price for this category",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="base price",
                    ),
                ),
                (
                    "deposit_percentage",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Required deposit percentage for this category",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="deposit percentage",
                    ),
                ),
                (
                    "min_production_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Minimum days required to produce items in this category",
                        verbose_name="minimum production days",
                    ),
                ),
                (
                    "max_production_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum days to produce items in this category",
                        verbose_name="maximum production days",
                    ),
                ),
                (
                    "requires_design",
                    models.BooleanField(
                        default=True,
                        help_text="Whether customers must upload a design file",
                        verbose_name="requires design file",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Whether pre-orders need admin approval before production",
                        verbose_name="requires approval",
                    ),
                ),
                (
                    "allow_rush_order",
                    models.BooleanField(
                        default=True,
                        help_text="Whether rush production is available",
                        verbose_name="allow rush order",
                    ),
                ),
                (
                    "rush_order_fee_percentage",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Additional percentage charged for rush orders",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="rush order fee percentage",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum quantity"
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="maximum quantity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "pre-order category",
                "verbose_name_plural": "pre-order categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PreOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preorder_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="pre-order number",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="full name"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the order",
                        max_length=300,
                        verbose_name="order title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what you want",
                        verbose_name="detailed description",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Any special requirements or instructions",
                        verbose_name="special instructions",
                    ),
                ),
                (
                    "gift_message",
                    models.TextField(
                        blank=True,
                        help_text="Message to include if this is a gift",
                        verbose_name="gift message",
                    ),
                ),
                ("is_gift", models.BooleanField(default=False, verbose_name="is gift")),
                (
                    "gift_wrap",
                    models.BooleanField(default=False, verbose_name="gift wrap"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("quoted", "Quote Provided"),
                            ("quote_accepted", "Quote Accepted"),
                            ("quote_rejected", "Quote Rejected"),
                            ("deposit_pending", "Deposit Pending"),
                            ("deposit_paid", "Deposit Paid"),
                            ("in_production", "In Production"),
                            ("quality_check", "Quality Check"),
                            ("awaiting_approval", "Awaiting Customer Approval"),
                            ("revision_requested", "Revision Requested"),
                            ("final_payment_pending", "Final Payment Pending"),
                            ("completed", "Completed"),
                            ("ready_to_ship", "Ready to Ship"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("on_hold", "On Hold"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_rush_order",
                    models.BooleanField(default=False, verbose_name="rush order"),
                ),
                (
                    "rush_order_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="rush order fee",
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="estimated price",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="final price",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="shipping cost",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "deposit_required",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="deposit required",
                    ),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="deposit paid",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total amount paid",
                    ),
                ),
                (
                    "amount_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="amount remaining",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "shipping_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="shipping first name"
                    ),
                ),
                (
                    "shipping_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="shipping last name"
                    ),
                ),
                (
                    "shipping_address_line_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="shipping address line 1",
                    ),
                ),
                (
                    "shipping_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="shipping address line 2",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="shipping city"
                    ),
                ),
                (
                    "shipping_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="shipping state"
                    ),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="shipping postal code"
                    ),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="shipping country"
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping"),
                            ("express", "Express Shipping"),
                            ("overnight", "Overnight Shipping"),
                            ("pickup", "Store Pickup"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="shipping method",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="tracking number"
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, verbose_name="tracking URL"),
                ),
                (
                    "requested_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="requested delivery date"
                    ),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="estimated completion date"
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="actual completion date"
                    ),
                ),
                (
                    "production_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="production start date"
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="customer notes"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="admin notes"),
                ),
                (
                    "production_notes",
                    models.TextField(blank=True, verbose_name="production notes"),
                ),
                (
                    "quote_valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="quote valid until"
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(blank=True, verbose_name="quote notes"),
                ),
                (
                    "revision_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="revision count"
                    ),
                ),
                (
                    "max_revisions",
                    models.PositiveIntegerField(
                        default=3, verbose_name="max revisions allowed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "quoted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="quoted at"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "production_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="production started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="shipped at"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How the customer found us (referral, social, etc.)",
                        max_length=50,
                        verbose_name="source",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM campaign"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to handle this pre-order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_preorders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "base_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional product to base the custom order on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorders",
                        to="catalog.product",
                        verbose_name="base product",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorders",
                        to="promotions.coupon",
                        verbose_name="coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preorders",
                        to="preorders.preordercategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order",
                "verbose_name_plural": "pre-orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=apps.preorders.models.preorder_design_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "ai",
                                    "psd",
                                    "svg",
                                    "eps",
                                    "cdr",
                                    "zip",
                                    "rar",
                                ]
                            )
                        ],
                        verbose_name="design file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Upload"),
                            ("admin", "Admin Upload"),
                            ("final", "Final Design"),
                            ("proof", "Proof"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="design type",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="current version"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_designs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_designs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order design",
                "verbose_name_plural": "pre-order designs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="item name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total price",
                    ),
                ),
                (
                    "customization_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="customization details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order item",
                "verbose_name_plural": "pre-order items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_from_customer",
                    models.BooleanField(default=True, verbose_name="from customer"),
                ),
                (
                    "is_from_system",
                    models.BooleanField(default=False, verbose_name="system message"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="preorders/messages/",
                        verbose_name="attachment",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_preorder_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order message",
                "verbose_name_plural": "pre-order messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("text", "Single Line Text"),
                            ("textarea", "Multi-line Text"),
                            ("number", "Number"),
                            ("select", "Dropdown Select"),
                            ("multiselect", "Multi-Select"),
                            ("checkbox", "Checkbox"),
                            ("color", "Color Picker"),
                            ("file", "File Upload"),
                            ("date", "Date Picker"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="option type",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="required"),
                ),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="minimum length"
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum length"
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional cost for this option",
                        max_digits=10,
                        verbose_name="price modifier",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="placeholder text"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="help text"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="preorders.preordercategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order option",
                "verbose_name_plural": "pre-order options",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderOptionChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="value")),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="display name"),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="price modifier",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for color options",
                        max_length=7,
                        verbose_name="color code",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="preorder_option_choices/",
                        verbose_name="image",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="preorders.preorderoption",
                        verbose_name="option",
                    ),
                ),
            ],
            options={
                "verbose_name": "option choice",
                "verbose_name_plural": "option choices",
                "ordering": ["option", "order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderOptionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_value", models.TextField(blank=True, verbose_name="text value")),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="number value",
                    ),
                ),
                (
                    "boolean_value",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="boolean value"
                    ),
                ),
                (
                    "date_value",
                    models.DateField(blank=True, null=True, verbose_name="date value"),
                ),
                (
                    "file_value",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="preorders/option_files/",
                        verbose_name="file value",
                    ),
                ),
                (
                    "price_modifier_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="price modifier applied",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "choice_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_values",
                        to="preorders.preorderoptionchoice",
                        verbose_name="selected choice",
                    ),
                ),
                (
                    "multi_choice_values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_submitted_values",
                        to="preorders.preorderoptionchoice",
                        verbose_name="selected choices",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values_submitted",
                        to="preorders.preorderoption",
                        verbose_name="option",
                    ),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_values",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order option value",
                "verbose_name_plural": "pre-order option values",
            },
        ),
        migrations.CreateModel(
            name="PreOrderPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("partial", "Partial Payment"),
                            ("final", "Final Payment"),
                            ("refund", "Refund"),
                        ],
                        default="deposit",
                        max_length=20,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit Card (Stripe)"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                        ],
                        default="stripe",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="transaction ID"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Stripe payment intent ID",
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stripe charge ID"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="gateway response"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "receipt_url",
                    models.URLField(blank=True, verbose_name="receipt URL"),
                ),
                (
                    "receipt_sent",
                    models.BooleanField(default=False, verbose_name="receipt sent"),
                ),
                (
                    "receipt_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="receipt sent at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_preorder_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order payment",
                "verbose_name_plural": "pre-order payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="quote number"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="base price"
                    ),
                ),
                (
                    "customization_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="customization cost",
                    ),
                ),
                (
                    "rush_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="rush fee",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="discount",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="shipping",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="tax",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="valid from"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="valid until")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "terms",
                    models.TextField(blank=True, verbose_name="terms and conditions"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "estimated_production_days",
                    models.PositiveIntegerField(
                        default=14, verbose_name="estimated production days"
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="estimated delivery date"
                    ),
                ),
                (
                    "customer_response_notes",
                    models.TextField(
                        blank=True, verbose_name="customer response notes"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order quote",
                "verbose_name_plural": "pre-order quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=apps.preorders.models.preorder_reference_path,
                        verbose_name="reference file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order reference",
                "verbose_name_plural": "pre-order references",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "revision_number",
                    models.PositiveIntegerField(verbose_name="revision number"),
                ),
                ("description", models.TextField(verbose_name="revision description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "additional_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional cost for this revision (if beyond free revisions)",
                        max_digits=10,
                        verbose_name="additional cost",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, verbose_name="admin response"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order revision",
                "verbose_name_plural": "pre-order revisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="from status"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(max_length=30, verbose_name="to status"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="system generated"),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="notification sent"
                    ),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="notification sent at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorder_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "preorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="preorders.preorder",
                        verbose_name="pre-order",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order status history",
                "verbose_name_plural": "pre-order status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOrderTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="template name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="preorder_templates/",
                        verbose_name="template image",
                    ),
                ),
                (
                    "default_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="default quantity"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="base price",
                    ),
                ),
                (
                    "estimated_days",
                    models.PositiveIntegerField(
                        default=14, verbose_name="estimated production days"
                    ),
                ),
                (
                    "default_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default option values as JSON",
                        verbose_name="default options",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(default=0, verbose_name="times used"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="preorders.preordercategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order template",
                "verbose_name_plural": "pre-order templates",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="preorder",
            index=models.Index(
                fields=["preorder_number"], name="preorders_p_preorde_644972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preorder",
            index=models.Index(
                fields=["status", "created_at"], name="preorders_p_status_98e203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preorder",
            index=models.Index(
                fields=["user", "status"], name="preorders_p_user_id_3f24b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preorder",
            index=models.Index(
                fields=["assigned_to", "status"], name="preorders_p_assigne_78127b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preorderoptionvalue",
            unique_together={("preorder", "option")},
        ),
        migrations.AlterUniqueTogether(
            name="preorderrevision",
            unique_together={("preorder", "revision_number")},
        ),
    ]
