# Generated by Django 5.2.11 on 2026-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preorders", "0002_historicalpreorder_historicalpreordercategory_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="preorderoption",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="preorders_option_category_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="preorderoptionchoice",
            constraint=models.UniqueConstraint(
                fields=("option", "value"),
                name="preorders_optionchoice_option_value_uniq",
            ),
        ),
    ]
