# Generated by Django 5.2.11 on 2026-04-23 22:12

import apps.preorders.models
import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0008_alter_preordercategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preordercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='preorder_categories/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='preorderdesign',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to=apps.preorders.models.preorder_design_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'ai', 'psd', 'svg', 'eps', 'cdr', 'zip', 'rar'])], verbose_name='design file'),
        ),
        migrations.AlterField(
            model_name='preordermessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='preorders/messages/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='preorderoptionchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='preorder_option_choices/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='preorderoptionvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='preorders/option_files/', verbose_name='file value'),
        ),
        migrations.AlterField(
            model_name='preorderreference',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to=apps.preorders.models.preorder_reference_path, verbose_name='reference file'),
        ),
        migrations.AlterField(
            model_name='preordertemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='preorder_templates/', verbose_name='template image'),
        ),
    ]
