# Generated by Django 5.2.1 on 2026-01-22 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Code",
                "verbose_name_plural": "Referral Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("discount", "Discount"),
                            ("store_credit", "Store Credit"),
                            ("free_product", "Free Product"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details of the reward (e.g., 10% off, $10 credit).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("earned", "Earned"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("earned_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referee_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The new user who was referred (received the reward).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_rewards_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="The referral code that generated this reward.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards_generated",
                        to="referral.referralcode",
                    ),
                ),
                (
                    "referrer_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who referred (earned the reward).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_rewards_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Reward",
                "verbose_name_plural": "Referral Rewards",
                "ordering": ["-created_at"],
            },
        ),
    ]
