# Generated by Django 5.2.1 on 2026-01-20 20:11

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productfiltergroup"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="bundles/",
                        verbose_name="image",
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="regular price",
                    ),
                ),
                (
                    "bundle_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="bundle price",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="featured"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="meta description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "bundle",
                "verbose_name_plural": "bundles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="promotions.bundle",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "bundle item",
                "verbose_name_plural": "bundle items",
                "ordering": ["display_order"],
                "unique_together": {("bundle", "product")},
            },
        ),
        migrations.AddField(
            model_name="bundle",
            name="products",
            field=models.ManyToManyField(
                related_name="bundles",
                through="promotions.BundleItem",
                to="catalog.product",
            ),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="promotions__is_acti_cc8a1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(
                fields=["is_featured"], name="promotions__is_feat_5cc65b_idx"
            ),
        ),
    ]
