# Generated by Django 5.2.11 on 2026-02-13 21:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_historicalbanner_historicalbundle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="overlay_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="overlay_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overlay opacity from 0 to 1 (e.g. 0.6).",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_border_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_border_radius",
            field=models.CharField(
                blank=True,
                help_text="CSS border-radius value (e.g. 24px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_border_width",
            field=models.CharField(
                blank=True, help_text="CSS border width (e.g. 1px).", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_height",
            field=models.CharField(
                blank=True,
                help_text="CSS height value for the banner (e.g. 420px, 60vh).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_max_width",
            field=models.CharField(
                blank=True,
                help_text="CSS max-width value for the banner (e.g. 1200px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="style_width",
            field=models.CharField(
                blank=True,
                help_text="CSS width value for the banner (e.g. 100%, 1200px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="overlay_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="overlay_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overlay opacity from 0 to 1 (e.g. 0.6).",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_border_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_border_radius",
            field=models.CharField(
                blank=True,
                help_text="CSS border-radius value (e.g. 24px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_border_width",
            field=models.CharField(
                blank=True, help_text="CSS border width (e.g. 1px).", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_height",
            field=models.CharField(
                blank=True,
                help_text="CSS height value for the banner (e.g. 420px, 60vh).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_max_width",
            field=models.CharField(
                blank=True,
                help_text="CSS max-width value for the banner (e.g. 1200px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="style_width",
            field=models.CharField(
                blank=True,
                help_text="CSS width value for the banner (e.g. 100%, 1200px).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
    ]
