# Generated by Django 5.2.11 on 2026-02-15 01:43

import apps.promotions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0002_translationglossary_contenttranslation_error_message_and_more"),
        ("promotions", "0003_banner_overlay_color_banner_overlay_opacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="currency",
            field=models.ForeignKey(
                db_column="currency",
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for bundle prices (e.g. BDT, USD).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_bundles",
                to="i18n.currency",
                to_field="code",
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="currency",
            field=models.ForeignKey(
                db_column="currency",
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for fixed/amount-based coupon values",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_coupons",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="couponusage",
            name="currency",
            field=models.ForeignKey(
                db_column="currency",
                default=apps.promotions.models.get_site_default_currency_code,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_coupon_usages",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="historicalbundle",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency",
                db_constraint=False,
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for bundle prices (e.g. BDT, USD).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="i18n.currency",
                to_field="code",
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="historicalcoupon",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency",
                db_constraint=False,
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for fixed/amount-based coupon values",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="historicalcouponusage",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency",
                db_constraint=False,
                default=apps.promotions.models.get_site_default_currency_code,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="historicalsale",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency",
                db_constraint=False,
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for fixed discount values",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="currency",
            field=models.ForeignKey(
                db_column="currency",
                default=apps.promotions.models.get_site_default_currency_code,
                help_text="Currency for fixed discount values",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_sales",
                to="i18n.currency",
                to_field="code",
            ),
        ),
    ]
