# Generated by Django 5.2.11 on 2026-04-08 05:02

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0007_alter_banner_image_alter_banner_image_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="banners/",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image_mobile",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="banners/mobile/",
            ),
        ),
        migrations.AlterField(
            model_name="bundle",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="bundles/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="sales/",
            ),
        ),
    ]
