# Generated by Django 5.2.11 on 2026-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_alter_banner_image_alter_banner_image_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal alignment for button.', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for button text (e.g. 12px, 0.875rem).', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_min_height',
            field=models.CharField(blank=True, help_text='CSS min-height for button (e.g. 40px).', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_padding',
            field=models.CharField(blank=True, help_text='CSS padding for button (e.g. 6px 16px).', max_length=30),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal alignment for title/subtitle content.', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_vertical_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='bottom', help_text='Vertical placement of title/subtitle/button block.', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for subtitle (e.g. 16px, 1rem).', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for title (e.g. 32px, 2rem).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal alignment for button.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for button text (e.g. 12px, 0.875rem).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_min_height',
            field=models.CharField(blank=True, help_text='CSS min-height for button (e.g. 40px).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_padding',
            field=models.CharField(blank=True, help_text='CSS padding for button (e.g. 6px 16px).', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal alignment for title/subtitle content.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='content_vertical_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='bottom', help_text='Vertical placement of title/subtitle/button block.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='subtitle_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for subtitle (e.g. 16px, 1rem).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='title_font_size',
            field=models.CharField(blank=True, help_text='CSS font-size for title (e.g. 32px, 2rem).', max_length=20),
        ),
    ]
