# Generated by Django 5.2.11 on 2026-04-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0011_banner_comprehensive_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="animation_type",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="autoplay_delay",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="background_position",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="background_size",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="button_background_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="button_hover_background_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="button_hover_text_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="button_text_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="container_opacity",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="hide_on_desktop",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="hide_on_mobile",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="mobile_height",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="size_preset",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="subtitle_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="subtitle_font_family",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title_color",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title_font_family",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="transition_duration",
        ),
    ]
