# Generated by Django 5.2.11 on 2026-04-18 19:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_remove_banner_animation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='animation_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fade', 'Fade In'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom', 'Zoom In'), ('bounce', 'Bounce'), ('flip', 'Flip')], default='fade', max_length=50, verbose_name='animation type'),
        ),
        migrations.AddField(
            model_name='banner',
            name='autoplay_delay',
            field=models.PositiveIntegerField(blank=True, help_text='Time before auto-rotating to next banner (leave empty to use default)', null=True, verbose_name='autoplay delay (seconds)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='background_position',
            field=models.CharField(blank=True, choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right')], default='center', max_length=30, verbose_name='background position'),
        ),
        migrations.AddField(
            model_name='banner',
            name='background_size',
            field=models.CharField(blank=True, choices=[('cover', 'Cover (default)'), ('contain', 'Contain'), ('auto', 'Auto'), ('100% 100%', 'Stretch')], default='cover', max_length=30, verbose_name='background size'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button background color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_hover_background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button hover background color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_hover_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button hover text color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button text color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='container_opacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall banner opacity from 0 (transparent) to 1 (opaque)', max_digits=3, null=True, verbose_name='container opacity'),
        ),
        migrations.AddField(
            model_name='banner',
            name='hide_on_desktop',
            field=models.BooleanField(default=False, verbose_name='hide on desktop'),
        ),
        migrations.AddField(
            model_name='banner',
            name='hide_on_mobile',
            field=models.BooleanField(default=False, verbose_name='hide on mobile'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_height',
            field=models.CharField(blank=True, help_text='CSS height for mobile devices (e.g., 280px, 50vh)', max_length=20, verbose_name='mobile height'),
        ),
        migrations.AddField(
            model_name='banner',
            name='size_preset',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('compact', 'Compact (280px)'), ('small', 'Small (350px)'), ('medium', 'Medium (420px)'), ('large', 'Large (520px)'), ('hero', 'Hero (600px)'), ('fullscreen', 'Fullscreen (100vh)'), ('custom', 'Custom (use height field)')], default='medium', max_length=30, verbose_name='size preset'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='subtitle color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('system-ui, -apple-system, sans-serif', 'System'), ('Georgia, serif', 'Georgia (Serif)'), ('Times New Roman, serif', 'Times (Serif)'), ('Helvetica, Arial, sans-serif', 'Helvetica (Sans)'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Montserrat, sans-serif', 'Montserrat'), ('Poppins, sans-serif', 'Poppins'), ('Playfair Display, serif', 'Playfair (Elegant)')], default='', max_length=100, verbose_name='subtitle font family'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='title color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('system-ui, -apple-system, sans-serif', 'System'), ('Georgia, serif', 'Georgia (Serif)'), ('Times New Roman, serif', 'Times (Serif)'), ('Helvetica, Arial, sans-serif', 'Helvetica (Sans)'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Montserrat, sans-serif', 'Montserrat'), ('Poppins, sans-serif', 'Poppins'), ('Playfair Display, serif', 'Playfair (Elegant)')], default='', max_length=100, verbose_name='title font family'),
        ),
        migrations.AddField(
            model_name='banner',
            name='transition_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of the transition animation (e.g., 0.5)', max_digits=4, null=True, verbose_name='transition duration (seconds)'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='animation_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fade', 'Fade In'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom', 'Zoom In'), ('bounce', 'Bounce'), ('flip', 'Flip')], default='fade', max_length=50, verbose_name='animation type'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='autoplay_delay',
            field=models.PositiveIntegerField(blank=True, help_text='Time before auto-rotating to next banner (leave empty to use default)', null=True, verbose_name='autoplay delay (seconds)'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='background_position',
            field=models.CharField(blank=True, choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right')], default='center', max_length=30, verbose_name='background position'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='background_size',
            field=models.CharField(blank=True, choices=[('cover', 'Cover (default)'), ('contain', 'Contain'), ('auto', 'Auto'), ('100% 100%', 'Stretch')], default='cover', max_length=30, verbose_name='background size'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button background color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_hover_background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button hover background color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_hover_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button hover text color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='button text color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='container_opacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall banner opacity from 0 (transparent) to 1 (opaque)', max_digits=3, null=True, verbose_name='container opacity'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='hide_on_desktop',
            field=models.BooleanField(default=False, verbose_name='hide on desktop'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='hide_on_mobile',
            field=models.BooleanField(default=False, verbose_name='hide on mobile'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='mobile_height',
            field=models.CharField(blank=True, help_text='CSS height for mobile devices (e.g., 280px, 50vh)', max_length=20, verbose_name='mobile height'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='size_preset',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('compact', 'Compact (280px)'), ('small', 'Small (350px)'), ('medium', 'Medium (420px)'), ('large', 'Large (520px)'), ('hero', 'Hero (600px)'), ('fullscreen', 'Fullscreen (100vh)'), ('custom', 'Custom (use height field)')], default='medium', max_length=30, verbose_name='size preset'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='subtitle color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='subtitle_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('system-ui, -apple-system, sans-serif', 'System'), ('Georgia, serif', 'Georgia (Serif)'), ('Times New Roman, serif', 'Times (Serif)'), ('Helvetica, Arial, sans-serif', 'Helvetica (Sans)'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Montserrat, sans-serif', 'Montserrat'), ('Poppins, sans-serif', 'Poppins'), ('Playfair Display, serif', 'Playfair (Elegant)')], default='', max_length=100, verbose_name='subtitle font family'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='title_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='title color'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='title_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('system-ui, -apple-system, sans-serif', 'System'), ('Georgia, serif', 'Georgia (Serif)'), ('Times New Roman, serif', 'Times (Serif)'), ('Helvetica, Arial, sans-serif', 'Helvetica (Sans)'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Montserrat, sans-serif', 'Montserrat'), ('Poppins, sans-serif', 'Poppins'), ('Playfair Display, serif', 'Playfair (Elegant)')], default='', max_length=100, verbose_name='title font family'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='transition_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of the transition animation (e.g., 0.5)', max_digits=4, null=True, verbose_name='transition duration (seconds)'),
        ),
    ]
