# Generated by Django 5.2.11 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0014_alter_banner_image_alter_banner_image_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image_mobile",
            field=models.ImageField(blank=True, null=True, upload_to="banners/mobile/"),
        ),
        migrations.AlterField(
            model_name="bundle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bundles/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="sales/"),
        ),
    ]
