# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Session key for anonymous visitors (if user isn't authenticated).",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("purchase", "Purchase"),
                            ("cart_add", "Cart Add"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight or value for the event (e.g. 1.0 for view, higher for purchase).",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "occurred_at"],
                        name="recommendat_event_7efcf8_idx",
                    ),
                    models.Index(
                        fields=["product"], name="recommendat_product_e77655_idx"
                    ),
                    models.Index(
                        fields=["user"], name="recommendat_user_id_4e40a0_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="recommendat_session_61deee_idx"
                    ),
                    models.Index(
                        fields=["product", "event"],
                        name="recommendat_product_d3ffe5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "frequently_bought_together",
                                "Frequently Bought Together",
                            ),
                            ("similar", "Similar"),
                            ("personal", "Personal"),
                            ("trending", "Trending"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Normalized relevance score between 0.0 and 1.0 (higher is better).",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="rule_based",
                        help_text="Algorithm / model that produced this recommendation (e.g. 'rule_based', 'collab_filter').",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="catalog.product",
                    ),
                ),
                (
                    "recommended_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_by",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "indexes": [
                    models.Index(
                        fields=["product", "type", "-score"],
                        name="rec_product_type_score_idx",
                    ),
                    models.Index(
                        fields=["recommended_product"],
                        name="rec_recommended_product_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-score"], name="rec_active_score_idx"
                    ),
                    models.Index(fields=["type", "score"], name="rec_type_score_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0.0), ("score__lte", 1.0)),
                        name="recommendation_score_range",
                    )
                ],
                "unique_together": {("product", "recommended_product", "type")},
            },
        ),
    ]
