# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit/Debit Card (Stripe)"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("cod", "Cash on Delivery"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="payment-icons/",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for icon (e.g., 'card', 'bkash')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color theme: blue, pink, orange, green, gray",
                        max_length=20,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("none", "No Fee"),
                            ("flat", "Flat Fee"),
                            ("percent", "Percentage"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fee_text",
                    models.CharField(
                        blank=True,
                        help_text="Display text for fee (e.g., '৳20 fee')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported currency codes. Empty means all currencies.",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported country codes. Empty means all countries.",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Public/publishable key where applicable (store secrets securely)",
                        max_length=255,
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret key (store encrypted in production, e.g., a secrets manager)",
                        max_length=255,
                    ),
                ),
                ("merchant_id", models.CharField(blank=True, max_length=100)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                (
                    "is_sandbox",
                    models.BooleanField(
                        default=True, help_text="Use sandbox/test mode"
                    ),
                ),
                (
                    "ssl_store_id",
                    models.CharField(
                        blank=True, help_text="SSLCommerz store id", max_length=200
                    ),
                ),
                (
                    "ssl_store_passwd",
                    models.CharField(
                        blank=True,
                        help_text="SSLCommerz store password (treat as secret)",
                        max_length=200,
                    ),
                ),
                (
                    "bkash_mode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="bKash mode (sandbox/live)",
                        max_length=20,
                    ),
                ),
                (
                    "bkash_app_key",
                    models.CharField(
                        blank=True,
                        help_text="bKash app key (store securely)",
                        max_length=255,
                    ),
                ),
                (
                    "bkash_app_secret",
                    models.CharField(
                        blank=True,
                        help_text="bKash app secret (store securely)",
                        max_length=255,
                    ),
                ),
                (
                    "bkash_username",
                    models.CharField(
                        blank=True, help_text="bKash API username", max_length=255
                    ),
                ),
                (
                    "bkash_password",
                    models.CharField(
                        blank=True,
                        help_text="bKash API password or secret",
                        max_length=255,
                    ),
                ),
                (
                    "nagad_merchant_id",
                    models.CharField(
                        blank=True, help_text="Nagad merchant id", max_length=255
                    ),
                ),
                (
                    "nagad_public_key",
                    models.TextField(blank=True, help_text="Nagad public key (PEM)"),
                ),
                (
                    "nagad_private_key",
                    models.TextField(blank=True, help_text="Nagad private key (PEM)"),
                ),
                (
                    "supports_partial",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Supports partial payments / splits",
                    ),
                ),
                (
                    "supports_recurring",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Supports recurring payments/subscriptions",
                    ),
                ),
                (
                    "supports_bnpl",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Supports BNPL provider integration",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to customer after selecting this payment method",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_routing_number", models.CharField(blank=True, max_length=50)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BNPLProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="payments_bn_code_fef684_idx"),
                    models.Index(
                        fields=["is_active"], name="payments_bn_is_acti_d180b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank", "Bank Account"),
                            ("paypal", "PayPal"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                ("card_brand", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "card_last_four",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("card_exp_month", models.IntegerField(blank=True, null=True)),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "billing_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        default="BDT",
                        help_text="Primary currency is BDT (Bangladeshi Taka)",
                        max_length=3,
                    ),
                ),
                ("method_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type reported by gateway (e.g., payment_success, refund)",
                        max_length=100,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gateway reference id (transaction id)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("attempt_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional external subscription id reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_charges",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("fraudulent", "Fraudulent"),
                            ("requested_by_customer", "Requested by Customer"),
                            ("product_issue", "Product Issue"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="payments_au_user_id_f2d761_idx"
                    ),
                    models.Index(
                        fields=["action"], name="payments_au_action_c5cf25_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_au_created_8e64cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BNPLAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("approved", models.BooleanField(db_index=True, default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="payments.bnplprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="payments_bn_user_id_5a46eb_idx"
                    ),
                    models.Index(
                        fields=["provider_reference"],
                        name="payments_bn_provide_6d6f88_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BkashCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_key", models.CharField(blank=True, max_length=255)),
                ("app_secret", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("auth_token", models.CharField(blank=True, max_length=1024)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bkash_credentials",
                        to="payments.paymentgateway",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token_expires_at"],
                        name="payments_bk_token_e_953f9b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated unique code",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Links",
                "indexes": [
                    models.Index(fields=["code"], name="payments_pa_code_e48d0c_idx"),
                    models.Index(
                        fields=["is_active"], name="payments_pa_is_acti_6c5616_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="payments_pa_expires_3a87cb_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_b50ce6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="payments_pa_stripe__6fe52c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "-created_at"], name="payments_pa_order_i_288dd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["gateway", "-created_at"], name="payments_pa_gateway_d63e0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payments_pa_referen_72073c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["order"], name="payments_pa_order_i_d65105_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment"], name="payments_pa_payment_0e8e31_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymenttransaction",
            unique_together={("gateway", "reference")},
        ),
        migrations.AddIndex(
            model_name="recurringcharge",
            index=models.Index(
                fields=["subscription"], name="payments_re_subscri_5d4d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringcharge",
            index=models.Index(fields=["status"], name="payments_re_status_50869a_idx"),
        ),
        migrations.AddIndex(
            model_name="recurringcharge",
            index=models.Index(
                fields=["attempt_at"], name="payments_re_attempt_59d7d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringcharge",
            index=models.Index(
                fields=["payment"], name="payments_re_payment_cdd366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringcharge",
            index=models.Index(
                fields=["stripe_subscription_id"], name="payments_re_stripe__df8c65_idx"
            ),
        ),
    ]
