# Generated by Django 5.2.10 on 2026-02-04 01:41

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="payment-icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
