# Generated by Django 5.2.11 on 2026-04-04 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_paymentgateway_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="payment-icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
