# Generated by Django 5.2.11 on 2026-04-08 05:02

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_paymentgateway_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="payment-icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
