# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_views", models.PositiveIntegerField(default=0)),
                (
                    "time_on_cart",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds spent on cart page"
                    ),
                ),
                ("checkout_attempts", models.PositiveIntegerField(default=0)),
                ("items_added", models.PositiveIntegerField(default=0)),
                ("items_removed", models.PositiveIntegerField(default=0)),
                ("items_saved_for_later", models.PositiveIntegerField(default=0)),
                ("quantity_changes", models.PositiveIntegerField(default=0)),
                ("coupons_tried", models.PositiveIntegerField(default=0)),
                ("coupons_applied", models.PositiveIntegerField(default=0)),
                ("coupons_failed", models.PositiveIntegerField(default=0)),
                ("first_source", models.CharField(blank=True, max_length=100)),
                ("last_source", models.CharField(blank=True, max_length=100)),
                ("first_item_added", models.DateTimeField(blank=True, null=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Cart Analytics",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_at_add",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Price lock expiry", null=True
                    ),
                ),
                (
                    "locked_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("gift_wrap", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, max_length=500)),
                ("gift_recipient_name", models.CharField(blank=True, max_length=200)),
                ("gift_recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "customer_note",
                    models.TextField(
                        blank=True,
                        help_text="Customer notes for this item",
                        max_length=500,
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(
                        blank=True, help_text="Internal notes", max_length=500
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Item priority for display ordering"
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                            ("bimonthly", "Every 2 Months"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "added_from",
                    models.CharField(
                        choices=[
                            ("product_page", "Product Page"),
                            ("category", "Category Page"),
                            ("search", "Search Results"),
                            ("wishlist", "Wishlist"),
                            ("recommendation", "Recommendation"),
                            ("quick_view", "Quick View"),
                            ("buy_again", "Buy Again"),
                            ("cart_drawer", "Cart Drawer"),
                            ("api", "API"),
                            ("other", "Other"),
                        ],
                        default="product_page",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_wrap_enabled", models.BooleanField(default=True)),
                (
                    "gift_wrap_amount",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "gift_wrap_label",
                    models.CharField(blank=True, default="Gift Wrap", max_length=100),
                ),
                ("cart_expiry_days", models.PositiveIntegerField(default=30)),
                (
                    "price_lock_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable price lock feature"
                    ),
                ),
                (
                    "price_lock_duration_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Default price lock duration"
                    ),
                ),
                (
                    "price_lock_auto_apply",
                    models.BooleanField(
                        default=False, help_text="Auto-apply price lock on add"
                    ),
                ),
                ("stock_reservation_enabled", models.BooleanField(default=True)),
                ("stock_reservation_minutes", models.PositiveIntegerField(default=30)),
                (
                    "minimum_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "minimum_order_message",
                    models.CharField(
                        blank=True,
                        default="Minimum order amount not met",
                        max_length=255,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2, default=3000.0, max_digits=10
                    ),
                ),
                (
                    "free_shipping_message",
                    models.CharField(
                        blank=True,
                        default="Free delivery on orders over ৳2,000",
                        max_length=255,
                    ),
                ),
                ("max_items_per_cart", models.PositiveIntegerField(default=50)),
                ("max_quantity_per_item", models.PositiveIntegerField(default=10)),
                (
                    "abandoned_cart_threshold_hours",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "abandoned_cart_reminder_delay_hours",
                    models.PositiveIntegerField(default=24),
                ),
                (
                    "abandoned_cart_max_reminders",
                    models.PositiveIntegerField(default=3),
                ),
                ("abandoned_cart_discount_enabled", models.BooleanField(default=True)),
                (
                    "abandoned_cart_discount_percent",
                    models.PositiveIntegerField(default=10),
                ),
                ("default_currency", models.CharField(default="BDT", max_length=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cart Settings",
                "verbose_name_plural": "Cart Settings",
            },
        ),
        migrations.CreateModel(
            name="CheckoutEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Checkout Started"),
                            ("info_submitted", "Information Submitted"),
                            ("shipping_selected", "Shipping Selected"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("order_created", "Order Created"),
                            ("abandoned", "Checkout Abandoned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "security_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("shipping_first_name", models.CharField(blank=True, max_length=100)),
                ("shipping_last_name", models.CharField(blank=True, max_length=100)),
                ("shipping_company", models.CharField(blank=True, max_length=200)),
                ("shipping_email", models.EmailField(blank=True, max_length=254)),
                ("shipping_phone", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                ("billing_same_as_shipping", models.BooleanField(default=True)),
                ("billing_first_name", models.CharField(blank=True, max_length=100)),
                ("billing_last_name", models.CharField(blank=True, max_length=100)),
                ("billing_company", models.CharField(blank=True, max_length=200)),
                (
                    "billing_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "billing_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "billing_country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping (5-7 days)"),
                            ("express", "Express Shipping (2-3 days)"),
                            ("overnight", "Overnight Shipping"),
                            ("pickup", "Store Pickup"),
                            ("free", "Free Shipping"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit/Debit Card (Stripe)"),
                            ("paypal", "PayPal"),
                            ("cod", "Cash on Delivery"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_client_secret", models.CharField(blank=True, max_length=255)),
                ("paypal_order_id", models.CharField(blank=True, max_length=255)),
                ("bkash_payment_id", models.CharField(blank=True, max_length=255)),
                ("nagad_payment_id", models.CharField(blank=True, max_length=255)),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_gift", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, max_length=500)),
                ("gift_wrap", models.BooleanField(default=False)),
                (
                    "gift_wrap_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("order_notes", models.TextField(blank=True)),
                ("delivery_instructions", models.TextField(blank=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tax_included", models.BooleanField(default=False)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=10),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("cart", "Cart"),
                            ("information", "Information"),
                            ("shipping", "Shipping"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="cart",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("converted_to_order", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-reserved_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="For guest alerts", max_length=254
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("any", "Any price drop"),
                            ("threshold", "When price drops below threshold"),
                            ("percentage", "When price drops by percentage"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "percentage_drop",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum percentage drop to alert",
                        null=True,
                    ),
                ),
                (
                    "price_at_creation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "lowest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedForLater",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_at_save", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionWishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionWishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "price_at_add",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "lowest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=2)),
                ("desired_quantity", models.PositiveIntegerField(default=1)),
                ("notify_on_sale", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-priority", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this shared cart",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("edit", "Can edit items"),
                            ("purchase", "Can purchase items"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        help_text="Optional password protection",
                        max_length=128,
                    ),
                ),
                (
                    "allowed_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed email addresses",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum number of uses", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Emoji icon for collection", max_length=10
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WishlistCollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "price_at_add",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lowest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "highest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Normal"),
                            (3, "High"),
                            (4, "Must Have"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "reminder_date",
                    models.DateField(
                        blank=True,
                        help_text="When to remind about this item",
                        null=True,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_message", models.CharField(blank=True, max_length=255)),
                ("desired_quantity", models.PositiveIntegerField(default=1)),
                ("notify_on_sale", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Notify when price drops to this",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Times product viewed from wishlist"
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-priority", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("share_token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_view", models.BooleanField(default=True)),
                ("allow_purchase", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cart_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("item_count", models.PositiveIntegerField()),
                ("items_snapshot", models.JSONField(default=list)),
                (
                    "recovery_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("recovery_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reminded", "Reminder Sent"),
                            ("recovered", "Recovered"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("next_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_discount_code", models.CharField(blank=True, max_length=50)),
                (
                    "recovery_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("abandoned_at", models.DateTimeField(auto_now_add=True)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("referrer", models.URLField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-abandoned_at"],
            },
        ),
    ]
