# Generated by Django 5.2.1 on 2026-01-20 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productfiltergroup"),
        ("commerce", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlistshare",
            options={
                "verbose_name": "wishlist share",
                "verbose_name_plural": "wishlist shares",
            },
        ),
        migrations.RenameField(
            model_name="wishlistshare",
            old_name="allow_view",
            new_name="allow_comments",
        ),
        migrations.RemoveField(
            model_name="wishlistshare",
            name="allow_purchase",
        ),
        migrations.RemoveField(
            model_name="wishlistshare",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="wishlistshare",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="wishlistshare",
            name="last_viewed_at",
        ),
        migrations.AddField(
            model_name="wishlistshare",
            name="allow_suggestions",
            field=models.BooleanField(
                default=True, help_text="Friends can suggest items to add"
            ),
        ),
        migrations.AddField(
            model_name="wishlistshare",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Anyone with link can view"
            ),
        ),
        migrations.AddField(
            model_name="wishlistshare",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_wishlists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wishlistshare",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="wishlistshare",
            name="share_token",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="wishlistshare",
            name="wishlist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share",
                to="commerce.wishlist",
            ),
        ),
        migrations.CreateModel(
            name="WishlistComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="commerce.wishlistcomment",
                    ),
                ),
                (
                    "wishlist_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="commerce.wishlistshare",
                    ),
                ),
            ],
            options={
                "verbose_name": "wishlist comment",
                "verbose_name_plural": "wishlist comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("added", "Added to Wishlist"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_suggestions",
                        to="catalog.product",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wishlist_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="commerce.wishlistshare",
                    ),
                ),
            ],
            options={
                "verbose_name": "wishlist suggestion",
                "verbose_name_plural": "wishlist suggestions",
                "ordering": ["-created_at"],
                "unique_together": {("wishlist_share", "suggested_by", "product")},
            },
        ),
    ]
