# Generated by Django 5.2.10 on 2026-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_alter_wishlistshare_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="payment_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="payment_fee_label",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
