# Generated by Django 5.2.11 on 2026-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_historicalabandonedcart_historicalcart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartsettings",
            name="gift_wrap_label",
            field=models.CharField(blank=True, default="Gift wrap", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalcartsettings",
            name="gift_wrap_label",
            field=models.CharField(blank=True, default="Gift wrap", max_length=100),
        ),
    ]
