# Generated by Django 5.2.11 on 2026-04-19 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_cartsettings_gift_wrap_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwishlist',
            name='anonymous_name',
            field=models.CharField(blank=True, help_text='Name for anonymous wishlist owner', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalwishlist',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Session wishlist expiry', null=True),
        ),
        migrations.AddField(
            model_name='historicalwishlist',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='anonymous_name',
            field=models.CharField(blank=True, help_text='Name for anonymous wishlist owner', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Session wishlist expiry', null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerce_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_key__exact', ''), ('user__isnull', False)), models.Q(('session_key__isnull', False), ('user__isnull', True)), _connector='OR'), name='wishlist_user_or_session'),
        ),
    ]
