# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255, unique=True)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("transactional", "Transactional"),
                            ("navigational", "Navigational"),
                        ],
                        default="informational",
                        max_length=24,
                    ),
                ),
                ("monthly_volume", models.IntegerField(blank=True, null=True)),
                ("is_target", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_target", "-monthly_volume", "term"],
            },
        ),
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(default="analysis", max_length=100)),
                ("top_urls", models.JSONField(default=list)),
                ("suggested_headings", models.JSONField(default=list)),
                ("top_terms", models.JSONField(default=list)),
                ("recommended_word_count", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_briefs",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SERPSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("search_engine", models.CharField(default="google", max_length=50)),
                ("position", models.PositiveSmallIntegerField()),
                ("url", models.CharField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("snippet", models.TextField(blank=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="scrape", max_length=50)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serp_snapshots",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword", "date", "position"],
            },
        ),
        migrations.CreateModel(
            name="GSCMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_metrics",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("keyword", "date")},
            },
        ),
        migrations.CreateModel(
            name="KeywordURLMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2000)),
                ("score", models.FloatField(default=0.0)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("transactional", "Transactional"),
                            ("navigational", "Navigational"),
                        ],
                        default="informational",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("keyword", "url")},
            },
        ),
    ]
