# Generated by Django 5.2.11 on 2026-02-10 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255, unique=True)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("transactional", "Transactional"),
                            ("navigational", "Navigational"),
                        ],
                        default="informational",
                        max_length=24,
                    ),
                ),
                ("monthly_volume", models.IntegerField(blank=True, null=True)),
                ("is_target", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_target", "-monthly_volume", "term"],
            },
        ),
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(default="analysis", max_length=100)),
                ("top_urls", models.JSONField(default=list)),
                ("suggested_headings", models.JSONField(default=list)),
                ("top_terms", models.JSONField(default=list)),
                ("recommended_word_count", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_briefs",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SERPSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("search_engine", models.CharField(default="google", max_length=50)),
                ("position", models.PositiveSmallIntegerField()),
                ("url", models.CharField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("snippet", models.TextField(blank=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="scrape", max_length=50)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serp_snapshots",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword", "date", "position"],
            },
        ),
        migrations.CreateModel(
            name="SitemapSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sitemap_type",
                    models.CharField(
                        choices=[
                            ("static", "Static Pages"),
                            ("products", "Products"),
                            ("categories", "Categories"),
                            ("blog", "Blog Posts"),
                        ],
                        help_text="Type of sitemap",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(help_text="URL of the sitemap", unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("indexed", "Indexed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current submission status",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the sitemap was submitted",
                        null=True,
                    ),
                ),
                (
                    "last_read",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the search engine last read the sitemap",
                        null=True,
                    ),
                ),
                (
                    "discovered_pages",
                    models.IntegerField(
                        default=0,
                        help_text="Number of pages discovered by search engine",
                    ),
                ),
                (
                    "discovered_videos",
                    models.IntegerField(
                        default=0,
                        help_text="Number of videos discovered by search engine",
                    ),
                ),
                (
                    "indexed_pages",
                    models.IntegerField(
                        default=0, help_text="Number of pages indexed by search engine"
                    ),
                ),
                (
                    "errors",
                    models.TextField(
                        blank=True, help_text="Any errors from the search engine"
                    ),
                ),
                (
                    "search_engines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of search engines this sitemap is submitted to",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sitemap Submission",
                "verbose_name_plural": "Sitemap Submissions",
                "ordering": ["-submitted_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sitemap_type", "status"],
                        name="seo_sitemap_sitemap_08da2f_idx",
                    ),
                    models.Index(
                        fields=["-submitted_at"], name="seo_sitemap_submitt_6f1ce9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GSCMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_metrics",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("keyword", "date")},
            },
        ),
        migrations.CreateModel(
            name="KeywordURLMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2000)),
                ("score", models.FloatField(default=0.0)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("transactional", "Transactional"),
                            ("navigational", "Navigational"),
                        ],
                        default="informational",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("keyword", "url")},
            },
        ),
        migrations.CreateModel(
            name="SitemapError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "affected_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs affected by this error",
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_logs",
                        to="seo.sitemapsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitemap Error",
                "verbose_name_plural": "Sitemap Errors",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "resolved"],
                        name="seo_sitemap_severit_4be222_idx",
                    )
                ],
            },
        ),
    ]
