# Generated by Django 5.2.11 on 2026-04-04 03:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0003_alter_artisan_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisan",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="artisans/photos/",
            ),
        ),
    ]
