# Generated by Django 5.2.11 on 2026-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0004_alter_artisan_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisan",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="artisans/photos/"
            ),
        ),
    ]
