# Generated by Django 5.2.11 on 2026-04-08 05:02

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0005_alter_artisan_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisan",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="artisans/photos/",
            ),
        ),
    ]
