# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import storages.backends.s3
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("i18n", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCarrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="carriers/",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        help_text="URL template for tracking. Use {tracking_number} as placeholder.",
                        max_length=500,
                    ),
                ),
                ("api_enabled", models.BooleanField(default=False)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("api_account_number", models.CharField(blank=True, max_length=100)),
                ("api_endpoint", models.URLField(blank=True)),
                (
                    "api_sandbox",
                    models.BooleanField(
                        default=True, help_text="Use sandbox/test mode"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("supports_real_time_rates", models.BooleanField(default=False)),
                ("supports_tracking", models.BooleanField(default=True)),
                ("supports_label_generation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Carrier",
                "verbose_name_plural": "Shipping Carriers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_address_line1", models.CharField(max_length=255)),
                ("origin_address_line2", models.CharField(blank=True, max_length=255)),
                ("origin_city", models.CharField(max_length=100)),
                ("origin_state", models.CharField(max_length=100)),
                ("origin_postal_code", models.CharField(max_length=20)),
                ("origin_country", models.CharField(default="US", max_length=2)),
                ("origin_phone", models.CharField(blank=True, max_length=20)),
                (
                    "default_weight_unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "default_dimension_unit",
                    models.CharField(
                        choices=[("cm", "Centimeters"), ("in", "Inches")],
                        default="cm",
                        max_length=5,
                    ),
                ),
                (
                    "default_package_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Default package weight when not specified",
                        max_digits=5,
                    ),
                ),
                ("show_delivery_estimates", models.BooleanField(default=True)),
                ("show_carrier_logos", models.BooleanField(default=True)),
                ("enable_free_shipping", models.BooleanField(default=False)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "free_shipping_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Countries eligible for free shipping",
                    ),
                ),
                (
                    "handling_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Business days to process order before shipping",
                    ),
                ),
                (
                    "cutoff_time",
                    models.TimeField(
                        blank=True,
                        help_text="Orders after this time processed next business day",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Settings",
                "verbose_name_plural": "Shipping Settings",
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "countries",
                    models.JSONField(
                        default=list,
                        help_text="List of ISO country codes (e.g., ['US', 'BD', 'GB'])",
                    ),
                ),
                (
                    "states",
                    models.JSONField(
                        default=list,
                        help_text="List of state/division names (e.g., ['Dhaka', 'Rangpur'])",
                    ),
                ),
                (
                    "cities",
                    models.JSONField(
                        default=list,
                        help_text="List of city/district names (e.g., ['Dhaka', 'Mirpur', 'Gulshan'])",
                    ),
                ),
                (
                    "postal_codes",
                    models.JSONField(
                        default=list,
                        help_text="List of postal code patterns (e.g., ['1200', '1205', '56*'])",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default zone for unmatched locations"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher priority zones are matched first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("label_created", "Label Created"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{length, width, height} in cm",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("label_url", models.URLField(blank=True)),
                ("label_format", models.CharField(blank=True, max_length=10)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("signature_required", models.BooleanField(default=False)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="signatures/",
                    ),
                ),
                ("signed_by", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.shippingcarrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Event",
                "verbose_name_plural": "Shipment Events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "carrier_service_code",
                    models.CharField(
                        blank=True,
                        help_text="Carrier-specific service code for API calls",
                        max_length=50,
                    ),
                ),
                ("min_delivery_days", models.PositiveIntegerField(default=3)),
                ("max_delivery_days", models.PositiveIntegerField(default=7)),
                (
                    "delivery_time_text",
                    models.CharField(
                        blank=True,
                        help_text="Display text (e.g., '3-7 business days')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_signature", models.BooleanField(default=False)),
                ("is_express", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Max dimensions: {length, width, height} in cm",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="methods",
                        to="shipping.shippingcarrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
            ),
        ),
        migrations.CreateModel(
            name="ShippingRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("product", "Specific Product"),
                            ("category", "Category"),
                            ("hazmat", "Hazardous Materials"),
                            ("oversized", "Oversized Items"),
                            ("fragile", "Fragile Items"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_ids", models.JSONField(blank=True, default=list)),
                ("category_ids", models.JSONField(blank=True, default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("block", "Block Shipping"),
                            ("surcharge", "Add Surcharge"),
                            ("signature", "Require Signature"),
                        ],
                        default="block",
                        max_length=20,
                    ),
                ),
                (
                    "surcharge_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message to display when restriction applies",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Restriction",
                "verbose_name_plural": "Shipping Restrictions",
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("weight", "Weight Based"),
                            ("price", "Price Based"),
                            ("item", "Per Item"),
                            ("free", "Free Shipping"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Base shipping cost",
                        max_digits=10,
                    ),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional cost per kg (for weight-based)",
                        max_digits=10,
                    ),
                ),
                (
                    "per_item_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional cost per item (for item-based)",
                        max_digits=10,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order subtotal for free shipping",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Weight tiers: [{max_weight, rate}, ...]",
                    ),
                ),
                (
                    "price_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Price tiers: [{max_price, rate}, ...]",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_rates",
                        to="i18n.currency",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
                "ordering": ["zone", "method", "base_rate"],
                "unique_together": {("zone", "method")},
            },
        ),
    ]
