# Generated by Django 5.2.11 on 2026-04-04 02:46

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_historicalshipment_historicalshipmentevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='carriers/'),
        ),
    ]
