# Generated by Django 5.2.11 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0008_alter_shipment_signature_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AlterField(
            model_name="shippingcarrier",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="carriers/"),
        ),
    ]
