# Generated by Django 5.2.11 on 2026-02-10 07:28

import apps.pages.models
import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="icon class"
                    ),
                ),
            ],
            options={
                "verbose_name": "blog category",
                "verbose_name_plural": "blog categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "blog tag",
                "verbose_name_plural": "blog tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterIncentive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="E.g., 10 for 10% off",
                        verbose_name="discount percentage",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        help_text="E.g., WELCOME10",
                        max_length=50,
                        unique=True,
                        verbose_name="discount code",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order amount required to use code",
                        max_digits=10,
                        null=True,
                        verbose_name="minimum order amount",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited",
                        null=True,
                        verbose_name="maximum uses",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, verbose_name="valid from"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valid until"
                    ),
                ),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("signups_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "newsletter incentive",
                "verbose_name_plural": "newsletter incentives",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("content", models.TextField(blank=True)),
                ("excerpt", models.TextField(blank=True, max_length=500)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True, max_length=300)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="pages/",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("landing", "Landing Page"),
                            ("contact", "Contact Page"),
                            ("about", "About Page"),
                            ("faq", "FAQ Page"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("show_in_header", models.BooleanField(default=False)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("menu_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["menu_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Bunoraa", max_length=100)),
                ("site_tagline", models.CharField(blank=True, max_length=200)),
                ("site_description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="site/",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="site/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="site/",
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("default_meta_title", models.CharField(blank=True, max_length=200)),
                (
                    "default_meta_description",
                    models.TextField(blank=True, max_length=300),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("currency_symbol", models.CharField(default="৳", max_length=5)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                ("footer_text", models.TextField(blank=True)),
                ("copyright_text", models.CharField(blank=True, max_length=200)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50)),
                ("custom_head_scripts", models.TextField(blank=True)),
                ("custom_body_scripts", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("source", models.CharField(default="website", max_length=50)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                ("excerpt", models.CharField(max_length=500, verbose_name="excerpt")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "featured_image",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="blog/",
                        verbose_name="featured image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Estimated reading time",
                        verbose_name="reading time (minutes)",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="meta keywords"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="pages.blogcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="pages.blogtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "blog post",
                "verbose_name_plural": "blog posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=100)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pages.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "blog comment",
                "verbose_name_plural": "blog comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image or SVG (preferred).",
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="site/social/",
                        validators=[apps.pages.models.SocialLink.validate_icon_file],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="pages.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubscriberIncentive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_code_generated",
                    models.CharField(
                        help_text="Unique code sent to this subscriber",
                        max_length=50,
                        unique=True,
                        verbose_name="discount code",
                    ),
                ),
                ("code_used", models.BooleanField(default=False)),
                ("code_used_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incentive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscribers",
                        to="pages.newsletterincentive",
                    ),
                ),
                (
                    "subscriber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentive_info",
                        to="pages.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscriber incentive",
                "verbose_name_plural": "subscriber incentives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="pages_blogp_status_3e07ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category"], name="pages_blogp_categor_165702_idx"
            ),
        ),
    ]
