# Generated by Django 5.2.11 on 2026-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="support_reply_time_note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
