# Generated by Django 5.2.11 on 2026-02-15 02:02

import django.db.models.deletion
from django.db import migrations, models


def _normalize_currency_code(value):
    code = str(value or "").strip().upper()
    if len(code) != 3:
        return "BDT"
    return code


def ensure_site_settings_currencies(apps, schema_editor):
    Currency = apps.get_model("i18n", "Currency")
    SiteSettings = apps.get_model("pages", "SiteSettings")
    HistoricalSiteSettings = apps.get_model("pages", "HistoricalSiteSettings")

    codes = {"BDT"}
    codes.update(
        _normalize_currency_code(code)
        for code in SiteSettings.objects.values_list("currency", flat=True)
    )
    codes.update(
        _normalize_currency_code(code)
        for code in HistoricalSiteSettings.objects.values_list("currency", flat=True)
    )

    for code in codes:
        defaults = {
            "name": "Bangladeshi Taka" if code == "BDT" else f"{code} Currency",
            "symbol": "Tk" if code == "BDT" else code,
            "is_active": True,
        }
        Currency.objects.get_or_create(code=code, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0002_translationglossary_contenttranslation_error_message_and_more"),
        ("pages", "0003_historicalblogcategory_historicalblogcomment_and_more"),
    ]

    operations = [
        migrations.RunPython(
            ensure_site_settings_currencies,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="historicalsitesettings",
            name="currency_symbol",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="currency_symbol",
        ),
        migrations.AlterField(
            model_name="historicalsitesettings",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency",
                db_constraint=False,
                default="BDT",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="i18n.currency",
                to_field="code",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="currency",
            field=models.ForeignKey(
                db_column="currency",
                default="BDT",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="page_site_settings",
                to="i18n.currency",
                to_field="code",
            ),
        ),
    ]
