# Generated by Django 5.2.11 on 2026-04-04 03:23

import apps.pages.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_blogpost_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="blog/",
                verbose_name="featured image",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="pages/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Upload an image or SVG (preferred).",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/social/",
                validators=[apps.pages.models.SocialLink.validate_icon_file],
            ),
        ),
    ]
