# Generated by Django 5.2.11 on 2026-04-10 01:12

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_blogpost_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(upload_to="blog/", verbose_name="featured image"),
        ),
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Upload an image or SVG (preferred).",
                null=True,
                upload_to="site/social/",
                validators=[apps.pages.models.SocialLink.validate_icon_file],
            ),
        ),
    ]
