# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("page_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("new_visitors", models.IntegerField(default=0)),
                ("returning_visitors", models.IntegerField(default=0)),
                ("product_views", models.IntegerField(default=0)),
                ("products_added_to_cart", models.IntegerField(default=0)),
                ("orders_count", models.IntegerField(default=0)),
                (
                    "orders_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("checkout_starts", models.IntegerField(default=0)),
                ("checkout_completions", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cart_abandonment_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("new_registrations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CartEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("add", "Add to Cart"),
                            ("remove", "Remove from Cart"),
                            ("update", "Update Quantity"),
                            ("checkout_start", "Start Checkout"),
                            ("checkout_complete", "Complete Checkout"),
                            ("abandoned", "Abandoned Cart"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="analytics_c_event_t_bac345_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.IntegerField(default=0)),
                ("product_views", models.IntegerField(default=0)),
                ("orders_count", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Category Stats",
                "ordering": ["-date"],
                "unique_together": {("category", "date")},
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("path", models.CharField(max_length=500)),
                (
                    "query_string",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("device_type", models.CharField(blank=True, max_length=20, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "time_on_page",
                    models.IntegerField(default=0, help_text="Time in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_p_created_44ec6b_idx"
                    ),
                    models.Index(
                        fields=["path", "-created_at"],
                        name="analytics_p_path_33d66e_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="analytics_p_session_1f2553_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.IntegerField(default=0)),
                ("add_to_cart_count", models.IntegerField(default=0)),
                ("orders_count", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Stats",
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_views",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="analytics_p_product_87066f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("results_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clicked_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_clicks",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_s_created_5d0a6f_idx"
                    ),
                    models.Index(fields=["query"], name="analytics_s_query_44edad_idx"),
                ],
            },
        ),
    ]
