# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/bundle_images/",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("component_sum", "Sum of Components"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/collection_images/",
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("visible_from", models.DateTimeField(blank=True, null=True)),
                ("visible_until", models.DateTimeField(blank=True, null=True)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("rules", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=5)),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "rate_to_default",
                    models.DecimalField(decimal_places=8, default=1, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.attribute",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "path",
                    models.CharField(db_index=True, editable=False, max_length=2000),
                ),
                ("depth", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/category_images/",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "aspect_ratio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1:1", "1:1"),
                            ("4:3", "4:3"),
                            ("16:9", "16:9"),
                            ("3:2", "3:2"),
                            ("free", "Free / responsive"),
                        ],
                        default="1:1",
                        max_length=10,
                    ),
                ),
                (
                    "aspect_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Width value used to compute aspect ratio. Leave blank to inherit from parent.",
                        max_digits=8,
                        null=True,
                        verbose_name="aspect width",
                    ),
                ),
                (
                    "aspect_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Height value used to compute aspect ratio. Leave blank to inherit from parent.",
                        max_digits=8,
                        null=True,
                        verbose_name="aspect height",
                    ),
                ),
                (
                    "aspect_unit",
                    models.CharField(
                        choices=[
                            ("ratio", "Ratio (unitless)"),
                            ("in", "Inches"),
                            ("ft", "Feet"),
                            ("cm", "Centimeters"),
                            ("mm", "Millimeters"),
                            ("px", "Pixels"),
                        ],
                        default="ratio",
                        max_length=10,
                        verbose_name="aspect unit",
                    ),
                ),
                ("product_count", models.IntegerField(db_index=True, default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="EcoCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_eco_slug_4772c3_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "choice"),
                            ("range", "range"),
                            ("boolean", "boolean"),
                            ("text", "text"),
                        ],
                        default="choice",
                        max_length=20,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        help_text="Optional list of values for choice facets",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_fac_slug_d51371_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryFacet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_facets",
                        to="catalog.category",
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_facets",
                        to="catalog.facet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.option",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=10)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1:1", "1:1"),
                            ("4:3", "4:3"),
                            ("16:9", "16:9"),
                            ("3:2", "3:2"),
                            ("free", "Free / responsive"),
                        ],
                        default="1:1",
                        max_length=10,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("allow_backorder", models.BooleanField(default=False)),
                ("low_stock_threshold", models.IntegerField(default=5)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("publish_from", models.DateTimeField(blank=True, null=True)),
                ("publish_until", models.DateTimeField(blank=True, null=True)),
                (
                    "carbon_footprint_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated carbon footprint in kg CO2e",
                        null=True,
                    ),
                ),
                (
                    "recycled_content_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sustainability_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("ethical_sourcing_notes", models.TextField(blank=True)),
                (
                    "material_breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="JSON describing materials and percentages",
                        null=True,
                    ),
                ),
                (
                    "is_mobile_optimized",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("voice_keywords", models.JSONField(blank=True, null=True)),
                (
                    "is_ar_compatible",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Product-level flag indicating presence of AR-ready 3D assets (USDZ/GLB).",
                    ),
                ),
                (
                    "image_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Optional visual embedding vector (list of floats) used for visual similarity lookups; populate via ML jobs in `ai_ml` app.",
                        null=True,
                    ),
                ),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_bestseller", models.BooleanField(db_index=True, default=False)),
                ("is_new_arrival", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.BigIntegerField(db_index=True, default=0)),
                ("sales_count", models.BigIntegerField(db_index=True, default=0)),
                ("reviews_count", models.IntegerField(db_index=True, default=0)),
                ("rating_count", models.IntegerField(db_index=True, default=0)),
                ("average_rating", models.FloatField(db_index=True, default=0.0)),
                ("reports_count", models.IntegerField(db_index=True, default=0)),
                ("cart_count", models.IntegerField(db_index=True, default=0)),
                ("wishlist_count", models.IntegerField(db_index=True, default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="catalog.category"
                    ),
                ),
                (
                    "eco_certifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="catalog.ecocertification",
                    ),
                ),
                (
                    "primary_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_products",
                        to="catalog.category",
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(blank=True, to="catalog.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/digital_assets/",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("license_key", models.CharField(blank=True, max_length=255)),
                (
                    "allowed_downloads",
                    models.IntegerField(
                        blank=True,
                        help_text="Max downloads allowed for this asset",
                        null=True,
                    ),
                ),
                ("downloads_count", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets_digital",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompareList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="compares", to="catalog.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="catalog.CollectionItem",
                to="catalog.product",
            ),
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_items",
                        to="catalog.bundle",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bundle",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_bundle",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="bundle",
            name="products",
            field=models.ManyToManyField(
                through="catalog.BundleItem", to="catalog.product"
            ),
        ),
        migrations.CreateModel(
            name="Product3DAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/3d_assets/",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("glb", "glb"), ("usdz", "usdz")],
                        default="glb",
                        max_length=10,
                    ),
                ),
                ("validated", models.BooleanField(default=False)),
                (
                    "poster_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/3d_posters/",
                    ),
                ),
                ("poster_alt", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_ar_compatible", models.BooleanField(db_index=True, default=False)),
                (
                    "ar_quicklook_url",
                    models.URLField(
                        blank=True, help_text="Optional AR Quick Look/Viewer URL"
                    ),
                ),
                (
                    "viewer_meta",
                    models.JSONField(
                        blank=True,
                        help_text="Viewer config (scale, orientation, lighting)",
                        null=True,
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets_3d",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.attributevalue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                through="catalog.ProductAttributeValue",
                to="catalog.attributevalue",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/product_images/",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "image_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Optional image embedding vector for visual search; list of floats.",
                        null=True,
                    ),
                ),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductImpression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.currency",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_pro_slug_d77ca8_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.producttype",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("verified_purchase", models.BooleanField(default=False)),
                ("helpful_votes", models.IntegerField(default=0)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/review_images/",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "eco_score",
                    models.IntegerField(
                        blank=True, help_text="Higher is more eco-friendly", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "packaging_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Extra packaging weight in kilograms",
                        max_digits=8,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Length of package in centimeters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Width of package in centimeters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Height of package in centimeters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "units_per_package",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of items this packaging typically holds",
                    ),
                ),
                (
                    "dimensional_weight_divisor",
                    models.IntegerField(
                        default=5000,
                        help_text="Divisor for dimensional weight calculation (cm^3 / divisor = kg)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="catalog_shi_name_05374a_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.shippingmaterial",
            ),
        ),
        migrations.CreateModel(
            name="Spotlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("category", "Category"),
                            ("collection", "Collection"),
                        ],
                        default="home",
                        max_length=30,
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotlights",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotlights",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("threshold", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("manual", "Manual Adjustment"),
                            ("reservation", "Reservation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.tag"
            ),
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("css_class", models.CharField(blank=True, max_length=100)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("target_raw", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "target_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/variant_images/",
                    ),
                ),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_images",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="VariantOptionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.optionvalue",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_option_values",
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productvariant",
            name="option_values",
            field=models.ManyToManyField(
                blank=True,
                related_name="variants",
                through="catalog.VariantOptionValue",
                to="catalog.optionvalue",
            ),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="wishlists", to="catalog.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_695af4_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_visible"], name="catalog_cat_is_visi_c46310_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["path"], name="catalog_cat_path_dea278_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["product_count"], name="catalog_cat_product_8822b3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                models.F("parent"),
                name="unique_category_parent_slug_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="categoryfacet",
            index=models.Index(
                fields=["category"], name="catalog_cat_categor_c32e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryfacet",
            index=models.Index(fields=["facet"], name="catalog_cat_facet_i_bf2f38_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="categoryfacet",
            unique_together={("category", "facet")},
        ),
        migrations.AlterUniqueTogether(
            name="optionvalue",
            unique_together={("option", "value")},
        ),
        migrations.AddIndex(
            model_name="digitalasset",
            index=models.Index(
                fields=["product"], name="catalog_dig_product_5f29b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionitem",
            unique_together={("collection", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="bundleitem",
            unique_together={("bundle", "product")},
        ),
        migrations.AddIndex(
            model_name="product3dasset",
            index=models.Index(
                fields=["product"], name="catalog_pro_product_ad591b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(
                fields=["product"], name="catalog_pro_product_291c9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(fields=["value"], name="catalog_pro_value_i_f34059_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("product", "value")},
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["embedding_updated_at"], name="catalog_pro_embeddi_c949a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimpression",
            index=models.Index(
                fields=["occurred_at"], name="catalog_pro_occurre_7f1e6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productprice",
            index=models.Index(
                fields=["currency"], name="catalog_pro_currenc_c85ead_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together={("product", "currency")},
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["expires_at"], name="catalog_res_expires_f775b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product"], name="catalog_rev_product_14bf05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="catalog_rev_user_id_82176f_idx"),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["created_at"], name="catalog_sto_created_f648e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["notified"], name="catalog_sto_notifie_40965d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_14fc6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["primary_category"], name="catalog_pro_primary_094831_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["views_count"], name="catalog_pro_views_c_dc81da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sales_count"], name="catalog_pro_sales_c_8d5aa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_ar_compatible"], name="catalog_pro_is_ar_c_9733c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sustainability_score"], name="catalog_pro_sustain_40ab28_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="unique_product_slug_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["slug"], name="catalog_bad_slug_24f93b_idx"),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["is_active", "start", "end"],
                name="catalog_bad_is_acti_af0d58_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantoptionvalue",
            unique_together={("variant", "option_value")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_187601_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("product",),
                name="unique_default_variant_per_product",
            ),
        ),
    ]
