# Generated by Django 5.2.1 on 2026-01-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0001_initial"),
        ("catalog", "0002_productfiltergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="artisan",
            field=models.ForeignKey(
                blank=True,
                help_text="The artisan who created this product.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="artisans.artisan",
            ),
        ),
    ]
