# Generated by Django 5.2.11 on 2026-02-21 13:41

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalcategorypricingprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1:1', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1:1', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1:1', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1:1', max_length=32),
        ),
        migrations.CreateModel(
            name='AspectRatioChoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='catalog_single_default_aspect_ratio')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAspectRatioChoice',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical aspect ratio choice',
                'verbose_name_plural': 'historical aspect ratio choices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
