# Generated by Django 5.2.1 on 2026-01-21 04:47

import django.db.models.deletion
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_artisan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMakingOf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="catalog/making_of/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to a video of this step (e.g., YouTube, Vimeo).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="making_of_steps",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Making Of Step",
                "verbose_name_plural": "Making Of Steps",
                "ordering": ["order"],
            },
        ),
    ]
