# Generated by Django 5.2.1 on 2026-01-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productmakingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_be_customized",
            field=models.BooleanField(
                default=False, help_text="Can this product be customized by customers?"
            ),
        ),
    ]
