# Generated by Django 5.2.11 on 2026-02-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_aspect_ratio_and_more'),
        ('i18n', '0002_translationglossary_contenttranslation_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency', db_constraint=False, default='BDT', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='i18n.currency', to_field='code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(db_column='currency', default='BDT', on_delete=django.db.models.deletion.PROTECT, related_name='catalog_products', to='i18n.currency', to_field='code'),
        ),
    ]
