# Generated by Django 5.2.11 on 2026-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_historicalproduct_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Disabled categories are excluded from catalog APIs and storefront listings.'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Disabled categories are excluded from catalog APIs and storefront listings.'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
    ]
