# Generated by Django 5.2.11 on 2026-02-24 20:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_sort_order_historicalcategory_sort_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReviewReport',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abusive Content'), ('off_topic', 'Off Topic'), ('misleading', 'Misleading'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical review report',
                'verbose_name_plural': 'historical review reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReviewVote',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_helpful', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical review vote',
                'verbose_name_plural': 'historical review votes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abusive Content'), ('off_topic', 'Off Topic'), ('misleading', 'Misleading'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='catalog_rev_product_14bf05_idx',
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='not_helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='would_recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreviewimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalreviewimage',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalreviewimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_reviews_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='would_recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'moderation_status', '-created_at'], name='catalog_rev_product_22d09c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderation_status', '-created_at'], name='catalog_rev_moderat_b3cb91_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_featured', '-created_at'], name='catalog_rev_product_4b86f5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['verified_purchase', 'rating'], name='catalog_rev_verifie_19fa73_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review', 'sort_order'], name='catalog_rev_review__e82a6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='catalog_review_unique_user_product'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='catalog_review_rating_between_1_5'),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='reporter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='review',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.review'),
        ),
        migrations.AddField(
            model_name='historicalreviewvote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewvote',
            name='review',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.review'),
        ),
        migrations.AddField(
            model_name='historicalreviewvote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_review_reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review', 'status'], name='catalog_rev_review__82e786_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='catalog_rev_status_005831_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('review', 'reporter'), name='catalog_review_open_report_unique'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['review', 'is_helpful'], name='catalog_rev_review__37b464_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['user'], name='catalog_rev_user_id_5bf3c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='catalog_review_vote_unique'),
        ),
    ]
