# Generated by Django 5.2.1 on 2026-01-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productquestion_productanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["path"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
