# Generated by Django 5.2.11 on 2026-02-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_migrate_legacy_reviews'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='historicalreviewimage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='historicalreviewreport',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreviewreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='historicalreviewreport',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='historicalreviewreport',
            name='review',
        ),
        migrations.RemoveField(
            model_name='historicalreviewvote',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreviewvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='historicalreviewvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalReview',
        ),
        migrations.DeleteModel(
            name='HistoricalReviewImage',
        ),
        migrations.DeleteModel(
            name='HistoricalReviewReport',
        ),
        migrations.DeleteModel(
            name='HistoricalReviewVote',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewReport',
        ),
        migrations.DeleteModel(
            name='ReviewVote',
        ),
            ],
        ),
    ]
