# Generated by Django 5.2.11 on 2026-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_bundle_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/bundle_images/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/category_images/"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/collection_images/"
            ),
        ),
        migrations.AlterField(
            model_name="customerphoto",
            name="image",
            field=models.ImageField(upload_to="catalog/customer_photos/"),
        ),
        migrations.AlterField(
            model_name="digitalasset",
            name="file",
            field=models.FileField(upload_to="catalog/digital_assets/"),
        ),
        migrations.AlterField(
            model_name="product3dasset",
            name="file",
            field=models.FileField(upload_to="catalog/3d_assets/"),
        ),
        migrations.AlterField(
            model_name="product3dasset",
            name="poster_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/3d_posters/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="catalog/product_images/"),
        ),
        migrations.AlterField(
            model_name="productmakingof",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/making_of/"
            ),
        ),
        migrations.AlterField(
            model_name="variantimage",
            name="image",
            field=models.ImageField(upload_to="catalog/variant_images/"),
        ),
    ]
