# Generated by Django 5.2.11 on 2026-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0007_alter_artisan_photo"),
        ("catalog", "0016_alter_bundle_image_alter_category_image_and_more"),
        ("i18n", "0002_translationglossary_contenttranslation_error_message_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_deleted", "-created_at"],
                name="catalog_prod_active_created",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured", "-created_at"],
                name="catalog_prod_featured",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_bestseller", "-sales_count"],
                name="catalog_prod_bestseller",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_new_arrival", "-created_at"],
                name="catalog_prod_new_arrival",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["primary_category", "is_active", "is_deleted", "-created_at"],
                name="catalog_prod_category",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-views_count"], name="catalog_prod_popular"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-sales_count"], name="catalog_prod_top_selling"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["average_rating", "reviews_count"], name="catalog_prod_rating"
            ),
        ),
    ]
