# Generated by Django 5.2.11 on 2026-04-23 22:11

import django.core.files.storage
import django.db.models.deletion
import pathlib
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_catalog_prod_active_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/bundle_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/category_images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/collection_images/'),
        ),
        migrations.AlterField(
            model_name='customerphoto',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/customer_photos/'),
        ),
        migrations.AlterField(
            model_name='digitalasset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/digital_assets/'),
        ),
        migrations.AlterField(
            model_name='product3dasset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/3d_assets/'),
        ),
        migrations.AlterField(
            model_name='product3dasset',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/3d_posters/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/product_images/'),
        ),
        migrations.AlterField(
            model_name='productmakingof',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/making_of/'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('D:/Website/Django-NodeJS/Bunoraa/media')), upload_to='catalog/variant_images/'),
        ),
        migrations.CreateModel(
            name='HistoricalSizeChart',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='E.g. "Men\'s T-Shirt Size Chart"', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('garment_type', models.CharField(choices=[('tops', 'Tops & Shirts'), ('bottoms', 'Bottoms & Pants'), ('dresses', 'Dresses & Gowns'), ('outerwear', 'Outerwear & Jackets'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('kids', 'Kids Clothing'), ('unisex', 'Unisex / General'), ('custom', 'Custom')], db_index=True, default='custom', help_text='Type of garment this chart applies to.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Optional guide text (e.g. "How to measure")')),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters'), ('mm', 'Millimeters')], default='in', max_length=5)),
                ('columns', models.JSONField(default=list, help_text='Ordered list of column headers, e.g. ["Size", "Chest", "Waist", "Length"]')),
                ('rows', models.JSONField(default=list, help_text='List of rows. Each row is a list of values matching column order.')),
                ('fit_notes', models.TextField(blank=True, help_text='Additional fit recommendations')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='If true, this chart is a fallback when no specific chart is assigned.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Size Chart',
                'verbose_name_plural': 'historical Size Charts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g. "Men\'s T-Shirt Size Chart"', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('garment_type', models.CharField(choices=[('tops', 'Tops & Shirts'), ('bottoms', 'Bottoms & Pants'), ('dresses', 'Dresses & Gowns'), ('outerwear', 'Outerwear & Jackets'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('kids', 'Kids Clothing'), ('unisex', 'Unisex / General'), ('custom', 'Custom')], db_index=True, default='custom', help_text='Type of garment this chart applies to.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Optional guide text (e.g. "How to measure")')),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters'), ('mm', 'Millimeters')], default='in', max_length=5)),
                ('columns', models.JSONField(default=list, help_text='Ordered list of column headers, e.g. ["Size", "Chest", "Waist", "Length"]')),
                ('rows', models.JSONField(default=list, help_text='List of rows. Each row is a list of values matching column order.')),
                ('fit_notes', models.TextField(blank=True, help_text='Additional fit recommendations')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='If true, this chart is a fallback when no specific chart is assigned.')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this size chart applies to (inherited by products in these categories).', related_name='size_charts', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Size Chart',
                'verbose_name_plural': 'Size Charts',
                'ordering': ['garment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSizeChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary chart shown by default.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_charts', to='catalog.product')),
                ('size_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.sizechart')),
            ],
            options={
                'verbose_name': 'Product Size Chart',
                'verbose_name_plural': 'Product Size Charts',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductSizeChart',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary chart shown by default.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product')),
                ('size_chart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.sizechart')),
            ],
            options={
                'verbose_name': 'historical Product Size Chart',
                'verbose_name_plural': 'historical Product Size Charts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='sizechart',
            index=models.Index(fields=['garment_type'], name='catalog_siz_garment_478fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='sizechart',
            index=models.Index(fields=['is_active'], name='catalog_siz_is_acti_3044b8_idx'),
        ),
        migrations.AddIndex(
            model_name='sizechart',
            index=models.Index(fields=['is_default'], name='catalog_siz_is_defa_49443a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsizechart',
            unique_together={('product', 'size_chart')},
        ),
    ]
