# Generated by Django 5.2.11 on 2026-04-04 03:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_alter_reviewimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="catalog/review_images/",
            ),
        ),
    ]
