# Generated by Django 5.2.11 on 2026-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_alter_reviewimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(upload_to="catalog/review_images/"),
        ),
    ]
