# Generated by Django 5.2.11 on 2026-04-08 05:02

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_alter_reviewimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath(
                        "D:/Website/Django-NodeJS/Bunoraa/media"
                    ),
                ),
                upload_to="catalog/review_images/",
            ),
        ),
    ]
