# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_refunded", "Order Refunded"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("review_approved", "Review Approved"),
                            ("review_rejected", "Review Rejected"),
                            ("price_drop", "Price Drop"),
                            ("back_in_stock", "Back In Stock"),
                            ("wishlist_sale", "Wishlist Item On Sale"),
                            ("account_created", "Account Created"),
                            ("password_reset", "Password Reset"),
                            ("promo_code", "Promo Code"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "html_template",
                    models.TextField(help_text="HTML template with placeholders"),
                ),
                (
                    "text_template",
                    models.TextField(help_text="Plain text template with placeholders"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_shipping_updates", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_price_drops", models.BooleanField(default=True)),
                ("email_back_in_stock", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("sms_order_updates", models.BooleanField(default=True)),
                ("sms_shipping_updates", models.BooleanField(default=True)),
                ("sms_promotions", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_order_updates", models.BooleanField(default=True)),
                ("push_promotions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=500, unique=True)),
                ("device_type", models.CharField(max_length=20)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_refunded", "Order Refunded"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("review_approved", "Review Approved"),
                            ("review_rejected", "Review Rejected"),
                            ("price_drop", "Price Drop"),
                            ("back_in_stock", "Back In Stock"),
                            ("wishlist_sale", "Wishlist Item On Sale"),
                            ("account_created", "Account Created"),
                            ("password_reset", "Password Reset"),
                            ("promo_code", "Promo Code"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "-created_at"],
                        name="notificatio_recipie_fe19f0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_18a272_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_refunded", "Order Refunded"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("review_approved", "Review Approved"),
                            ("review_rejected", "Review Rejected"),
                            ("price_drop", "Price Drop"),
                            ("back_in_stock", "Back In Stock"),
                            ("wishlist_sale", "Wishlist Item On Sale"),
                            ("account_created", "Account Created"),
                            ("password_reset", "Password Reset"),
                            ("promo_code", "Promo Code"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to relevant page", null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channels_sent",
                    models.JSONField(
                        default=list, help_text="Channels notification was sent to"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(fields=["type"], name="notificatio_type_ea918f_idx"),
                ],
            },
        ),
    ]
