# Generated by Django 5.2.1 on 2026-01-22 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productquestion_productanswer"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackInStockNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address to notify if user is not authenticated.",
                        max_length=254,
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        default=False, help_text="Has the customer been notified?"
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_requests",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who requested the notification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="back_in_stock_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific variant of the product requested (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_requests",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Back in Stock Notification Request",
                "verbose_name_plural": "Back in Stock Notification Requests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("product", "variant", "user"),
                        name="unique_back_in_stock_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("product", "variant", "email"),
                        name="unique_back_in_stock_email",
                    ),
                ],
            },
        ),
    ]
