# Generated by Django 5.2.11 on 2026-02-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_hardening"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_dedupe__f63021_idx",
            old_name="notificatio_dedupe_4f8a2f_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_categor_fd561f_idx",
            old_name="notificatio_categor_764ad0_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdelivery",
            new_name="notificatio_channel_edd073_idx",
            old_name="notificatio_channel_0b08c6_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdelivery",
            new_name="notificatio_notific_7707f8_idx",
            old_name="notificatio_notific_6a2c7e_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notificatio_notific_67a098_idx",
            old_name="notificatio_notific_0f7f7f_idx",
        ),
    ]
