# Generated by Django 5.2.1 on 2026-01-08 16:52

import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_conversations", models.PositiveIntegerField(default=0)),
                ("new_conversations", models.PositiveIntegerField(default=0)),
                ("resolved_conversations", models.PositiveIntegerField(default=0)),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("customer_messages", models.PositiveIntegerField(default=0)),
                ("agent_messages", models.PositiveIntegerField(default=0)),
                ("bot_messages", models.PositiveIntegerField(default=0)),
                ("avg_first_response_seconds", models.FloatField(default=0)),
                ("avg_resolution_time_seconds", models.FloatField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("category_breakdown", models.JSONField(default=dict)),
                ("agent_performance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Analytics",
                "verbose_name_plural": "Chat Analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChatSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_chat_enabled", models.BooleanField(default=True)),
                (
                    "offline_message",
                    models.TextField(
                        default="We are currently offline. Please leave a message and we will get back to you."
                    ),
                ),
                ("business_hours_enabled", models.BooleanField(default=False)),
                (
                    "business_hours",
                    models.JSONField(
                        default=dict,
                        help_text='{"monday": {"start": "09:00", "end": "18:00"}, ...}',
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Dhaka", max_length=50)),
                (
                    "welcome_message",
                    models.TextField(default="Hello! How can we help you today?"),
                ),
                (
                    "bot_name",
                    models.CharField(default="Bunoraa Assistant", max_length=50),
                ),
                (
                    "bot_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="chat/bot/",
                    ),
                ),
                ("ai_enabled", models.BooleanField(default=True)),
                ("ai_model", models.CharField(default="gpt-4", max_length=50)),
                ("ai_temperature", models.FloatField(default=0.7)),
                ("ai_max_tokens", models.PositiveIntegerField(default=500)),
                (
                    "ai_system_prompt",
                    models.TextField(
                        default="You are a helpful customer support assistant for Bunoraa, a handcrafted artisan marketplace. Be friendly, helpful, and concise."
                    ),
                ),
                ("auto_reply_delay_seconds", models.PositiveIntegerField(default=1)),
                (
                    "max_ai_responses_before_handoff",
                    models.PositiveIntegerField(default=5),
                ),
                ("notify_on_new_chat", models.BooleanField(default=True)),
                ("notify_on_customer_waiting", models.BooleanField(default=True)),
                (
                    "customer_waiting_threshold_minutes",
                    models.PositiveIntegerField(default=2),
                ),
                ("max_message_length", models.PositiveIntegerField(default=5000)),
                ("max_file_size_mb", models.PositiveIntegerField(default=10)),
                (
                    "allowed_file_types",
                    models.JSONField(
                        default=list,
                        help_text='["image/jpeg", "image/png", "application/pdf"]',
                    ),
                ),
                ("request_rating", models.BooleanField(default=True)),
                (
                    "rating_prompt",
                    models.CharField(
                        default="How would you rate your experience?", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Settings",
                "verbose_name_plural": "Chat Settings",
            },
        ),
        migrations.CreateModel(
            name="ChatAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                ("is_accepting_chats", models.BooleanField(default=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("max_concurrent_chats", models.PositiveIntegerField(default=5)),
                ("current_chat_count", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="List of category codes this agent can handle",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list, help_text="Languages the agent can support"
                    ),
                ),
                ("total_chats_handled", models.PositiveIntegerField(default=0)),
                ("avg_response_time_seconds", models.FloatField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("auto_accept", models.BooleanField(default=False)),
                ("notification_sound", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Agent",
                "verbose_name_plural": "Chat Agents",
            },
        ),
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "shortcut",
                    models.CharField(
                        help_text="Trigger shortcut, e.g., /greeting", max_length=50
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("order", "Order Inquiry"),
                            ("product", "Product Question"),
                            ("shipping", "Shipping & Delivery"),
                            ("returns", "Returns & Refunds"),
                            ("payment", "Payment Issue"),
                            ("technical", "Technical Support"),
                            ("general", "General Inquiry"),
                            ("complaint", "Complaint"),
                            ("feedback", "Feedback"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = shared across all agents",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="chat.chatagent",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "title"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("waiting", "Waiting for Agent"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("order", "Order Inquiry"),
                            ("product", "Product Question"),
                            ("shipping", "Shipping & Delivery"),
                            ("returns", "Returns & Refunds"),
                            ("payment", "Payment Issue"),
                            ("technical", "Technical Support"),
                            ("general", "General Inquiry"),
                            ("complaint", "Complaint"),
                            ("feedback", "Feedback"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="1=Urgent, 2=High, 3=Normal, 4=Low"
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("initial_message", models.TextField(blank=True)),
                (
                    "order_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        default="website",
                        help_text="website, mobile_app, whatsapp, etc.",
                        max_length=20,
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("is_bot_handling", models.BooleanField(default=True)),
                ("bot_handoff_requested", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("rating_comment", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="chat.chatagent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_from_customer", models.BooleanField(default=True)),
                ("is_from_bot", models.BooleanField(default=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("system", "System Message"),
                            ("ai", "AI Response"),
                            ("canned", "Canned Response"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like quick replies, buttons, etc.",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_delivered", models.BooleanField(default=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reactions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="chat/attachments/%Y/%m/",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="chat/thumbnails/%Y/%m/",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_indicators",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatagent",
            index=models.Index(
                fields=["is_online", "is_accepting_chats"],
                name="chat_chatag_is_onli_bb1593_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cannedresponse",
            unique_together={("agent", "shortcut")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["customer", "status"], name="chat_conver_custome_1205e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["agent", "status"], name="chat_conver_agent_i_a11f5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["status", "-last_message_at"],
                name="chat_conver_status_731933_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-created_at"], name="chat_conver_created_766071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read"],
                name="chat_messag_convers_7d694b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typingindicator",
            unique_together={("conversation", "user")},
        ),
    ]
