# Generated by Django 5.2.11 on 2026-02-10 21:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatagent",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for the chat agent",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="chat/agents/avatars/",
            ),
        ),
    ]
