# Generated by Django 5.2.11 on 2026-02-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatagent_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cannedresponse",
            options={"ordering": ["-use_count", "title"]},
        ),
        migrations.RenameField(
            model_name="cannedresponse",
            old_name="usage_count",
            new_name="use_count",
        ),
        migrations.AddField(
            model_name="cannedresponse",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cannedresponse",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cannedresponse",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatagent",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatagent",
            name="skills",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatanalytics",
            name="channel_breakdown",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="chatanalytics",
            name="hourly_breakdown",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="email_reply_from",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="max_concurrent_chats",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="support_inbox",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="wait_message",
            field=models.TextField(
                default="Thanks for reaching out. An agent will be with you shortly."
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("system", "System Message"),
                    ("ai", "AI Response"),
                    ("canned", "Canned Response"),
                    ("email", "Email"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
