# Generated by Django 5.2.11 on 2026-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_historicalcannedresponse_historicalchatagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='ai_model',
            field=models.CharField(default='Qwen/Qwen2.5-1.5B-Instruct', help_text='Local Hugging Face model ID or local model path', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalchatsettings',
            name='ai_model',
            field=models.CharField(default='Qwen/Qwen2.5-1.5B-Instruct', help_text='Local Hugging Face model ID or local model path', max_length=120),
        ),
    ]
