# Generated by Django 5.2.11 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_chatagent_avatar_alter_chatsettings_bot_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatagent",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for the chat agent",
                null=True,
                upload_to="chat/agents/avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="chatsettings",
            name="bot_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="chat/bot/"),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(upload_to="chat/attachments/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat/thumbnails/%Y/%m/"
            ),
        ),
    ]
